#include "linux_personality/linux_stub_symbols.h"
#include "kobox/shim.h"
#include "linux_subsystem/kvm/kvm_symbols.h"

#include <stdint.h>
#include <string.h>

static int kb_pm_suspend_default_s2idle;
static unsigned int kb_pm_suspend_global_flags;
static void *kb_console_list_head;
static void *kb_console_driver;
static int kb_fg_console;
static unsigned char kb_tasklist_lock[16];
static unsigned char kb_init_task[16384];
static unsigned int kb_overflowuid = 65534;
static unsigned int kb_overflowgid = 65534;
static unsigned char kb_tracepoint_dma_fence_emit[128];
static unsigned char kb_drm_gem_shmem_vm_ops[128];

static int kb_virtio_no_restricted_mem_acc(void *dev)
{
    (void)dev;
    return 0;
}

static void *kb_virtio_check_mem_acc_cb = (void *)(uintptr_t)&kb_virtio_no_restricted_mem_acc;

static uint64_t kb_stub_return_zero_u64(void)
{
    return 0;
}

__attribute__((naked)) static long kb_linux_get_user_1(void)
{
    __asm__ volatile(
        "test %rax, %rax\n"
        "jz 1f\n"
        "movzbl (%rax), %edx\n"
        "xor %eax, %eax\n"
        "ret\n"
        "1:\n"
        "xor %edx, %edx\n"
        "mov $-14, %eax\n"
        "ret\n");
}

__attribute__((naked)) static long kb_linux_get_user_2(void)
{
    __asm__ volatile(
        "test %rax, %rax\n"
        "jz 1f\n"
        "movzwl (%rax), %edx\n"
        "xor %eax, %eax\n"
        "ret\n"
        "1:\n"
        "xor %edx, %edx\n"
        "mov $-14, %eax\n"
        "ret\n");
}

__attribute__((naked)) static long kb_linux_get_user_4(void)
{
    __asm__ volatile(
        "test %rax, %rax\n"
        "jz 1f\n"
        "movl (%rax), %edx\n"
        "xor %eax, %eax\n"
        "ret\n"
        "1:\n"
        "xor %edx, %edx\n"
        "mov $-14, %eax\n"
        "ret\n");
}

__attribute__((naked)) static long kb_linux_get_user_8(void)
{
    __asm__ volatile(
        "test %rax, %rax\n"
        "jz 1f\n"
        "movq (%rax), %rdx\n"
        "xor %eax, %eax\n"
        "ret\n"
        "1:\n"
        "xor %edx, %edx\n"
        "mov $-14, %eax\n"
        "ret\n");
}

__attribute__((naked)) static long kb_linux_put_user_4(void)
{
    __asm__ volatile(
        "test %rcx, %rcx\n"
        "jz 1f\n"
        "movl %eax, (%rcx)\n"
        "xor %ecx, %ecx\n"
        "ret\n"
        "1:\n"
        "mov $-14, %ecx\n"
        "ret\n");
}

__attribute__((naked)) static long kb_linux_put_user_8(void)
{
    __asm__ volatile(
        "test %rcx, %rcx\n"
        "jz 1f\n"
        "movq %rax, (%rcx)\n"
        "xor %ecx, %ecx\n"
        "ret\n"
        "1:\n"
        "mov $-14, %ecx\n"
        "ret\n");
}

typedef struct kb_timespec64_stub {
    int64_t tv_sec;
    long tv_nsec;
} kb_timespec64_stub_t;

static kb_timespec64_stub_t kb_ns_to_timespec64_stub(int64_t nsec)
{
    kb_timespec64_stub_t ts;
    ts.tv_sec = nsec / 1000000000LL;
    ts.tv_nsec = (long)(nsec % 1000000000LL);
    if (ts.tv_nsec < 0) {
        ts.tv_nsec += 1000000000L;
        ts.tv_sec--;
    }
    return ts;
}

static void kb_dma_fence_init(
    void *fence,
    const void *ops,
    void *lock,
    uint64_t context,
    uint64_t seqno)
{
    enum {
        KB_DMA_FENCE_BYTES = 0x40,
        KB_DMA_FENCE_LOCK_OFFSET = 0x00,
        KB_DMA_FENCE_OPS_OFFSET = 0x08,
        KB_DMA_FENCE_CALLBACKS_OFFSET = 0x10,
        KB_DMA_FENCE_CONTEXT_OFFSET = 0x20,
        KB_DMA_FENCE_SEQNO_OFFSET = 0x28,
        KB_DMA_FENCE_REFCOUNT_OFFSET = 0x38,
    };
    if (fence == NULL) return;
    unsigned char *bytes = fence;
    memset(bytes, 0, KB_DMA_FENCE_BYTES);
    memcpy(bytes + KB_DMA_FENCE_LOCK_OFFSET, &lock, sizeof(lock));
    memcpy(bytes + KB_DMA_FENCE_OPS_OFFSET, &ops, sizeof(ops));
    void *callbacks = bytes + KB_DMA_FENCE_CALLBACKS_OFFSET;
    memcpy(bytes + KB_DMA_FENCE_CALLBACKS_OFFSET, &callbacks, sizeof(callbacks));
    memcpy(bytes + KB_DMA_FENCE_CALLBACKS_OFFSET + sizeof(callbacks), &callbacks, sizeof(callbacks));
    memcpy(bytes + KB_DMA_FENCE_CONTEXT_OFFSET, &context, sizeof(context));
    memcpy(bytes + KB_DMA_FENCE_SEQNO_OFFSET, &seqno, sizeof(seqno));
    const uint32_t refcount = 1;
    memcpy(bytes + KB_DMA_FENCE_REFCOUNT_OFFSET, &refcount, sizeof(refcount));
}

static const kb_linux_symbol_t stub_symbols[] = {
    {"__fentry__", (void *)(uintptr_t)&kb_noop_stub},
    {"__x86_return_thunk", (void *)(uintptr_t)&kb_noop_stub},
    {"___drm_dbg", (void *)(uintptr_t)&kb_noop_stub},
    {"__drm_err", (void *)(uintptr_t)&kb_noop_stub},
    {"pm_suspend_default_s2idle", (void *)(uintptr_t)&kb_pm_suspend_default_s2idle},
    {"pm_suspend_global_flags", (void *)(uintptr_t)&kb_pm_suspend_global_flags},
    {"pm_schedule_suspend", (void *)(uintptr_t)&kb_return_zero},
    {"ptp_clock_index", (void *)(uintptr_t)&kb_return_zero},
    {"ptp_clock_register", (void *)(uintptr_t)&kb_alloc_stub},
    {"ptp_clock_unregister", (void *)(uintptr_t)&kb_noop_stub},
    {"timecounter_cyc2time", (void *)(uintptr_t)&kb_stub_return_zero_u64},
    {"timecounter_init", (void *)(uintptr_t)&kb_noop_stub},
    {"timecounter_read", (void *)(uintptr_t)&kb_stub_return_zero_u64},
    {"pm_vt_switch_unregister", (void *)(uintptr_t)&kb_noop_stub},
    {"devres_close_group", (void *)(uintptr_t)&kb_noop_stub},
    {"devres_remove_group", (void *)(uintptr_t)&kb_noop_stub},
    {"_raw_read_lock", (void *)(uintptr_t)&kb_noop_stub},
    {"_raw_read_unlock", (void *)(uintptr_t)&kb_noop_stub},
    {"_raw_write_lock", (void *)(uintptr_t)&kb_noop_stub},
    {"_raw_write_trylock", (void *)(uintptr_t)&kb_return_one},
    {"_raw_write_unlock", (void *)(uintptr_t)&kb_noop_stub},
    {"__SCT__preempt_schedule", (void *)(uintptr_t)&kb_noop_stub},
    {"__SCT__preempt_schedule_notrace", (void *)(uintptr_t)&kb_noop_stub},
    {"___ratelimit", (void *)(uintptr_t)&kb_return_one},
    {"__do_once_done", (void *)(uintptr_t)&kb_noop_stub},
    {"__do_once_start", (void *)(uintptr_t)&kb_return_zero},
    {"__dynamic_pr_debug", (void *)(uintptr_t)&kb_noop_stub},
    {"__flush_workqueue", (void *)(uintptr_t)&kb_noop_stub},
    {"__refrigerator", (void *)(uintptr_t)&kb_noop_stub},
    {"__splice_from_pipe", (void *)(uintptr_t)&kb_return_zero},
    {"__mmap_lock_do_trace_acquire_returned", (void *)(uintptr_t)&kb_noop_stub},
    {"__mmap_lock_do_trace_released", (void *)(uintptr_t)&kb_noop_stub},
    {"__mmap_lock_do_trace_start_locking", (void *)(uintptr_t)&kb_noop_stub},
    {"__request_module", (void *)(uintptr_t)&kb_return_zero},
    {"__task_pid_nr_ns", (void *)(uintptr_t)&kb_return_zero},
    {"__ubsan_handle_shift_out_of_bounds", (void *)(uintptr_t)&kb_noop_stub},
    {"base64_decode", (void *)(uintptr_t)&kb_return_zero},
    {"console_device", (void *)(uintptr_t)&kb_return_zero},
    {"console_driver", (void *)(uintptr_t)&kb_console_driver},
    {"console_list", (void *)(uintptr_t)&kb_console_list_head},
    {"console_list_lock", (void *)(uintptr_t)&kb_noop_stub},
    {"console_list_unlock", (void *)(uintptr_t)&kb_noop_stub},
    {"console_lock", (void *)(uintptr_t)&kb_noop_stub},
    {"console_unlock", (void *)(uintptr_t)&kb_noop_stub},
    {"convert_art_to_tsc", (void *)(uintptr_t)&kb_return_zero},
    {"cpu_latency_qos_add_request", (void *)(uintptr_t)&kb_return_zero},
    {"cpu_latency_qos_remove_request", (void *)(uintptr_t)&kb_noop_stub},
    {"cpu_latency_qos_update_request", (void *)(uintptr_t)&kb_return_zero},
    {"cpufreq_get", (void *)(uintptr_t)&kb_return_zero},
    {"crc32_le", (void *)(uintptr_t)&kb_return_zero},
    {"crc32_be", (void *)(uintptr_t)&kb_return_zero},
    {"cachemode2protval", (void *)(uintptr_t)&kb_return_zero},
    {"dma_fence_init", (void *)(uintptr_t)&kb_dma_fence_init},
    {"dma_fence_release", (void *)(uintptr_t)&kb_noop_stub},
    {"dma_resv_add_fence", (void *)(uintptr_t)&kb_noop_stub},
    {"dma_unmap_resource", (void *)(uintptr_t)&kb_noop_stub},
    {"dma_unmap_sg_attrs", (void *)(uintptr_t)&kb_noop_stub},
    {"dma_sync_single_for_cpu", (void *)(uintptr_t)&kb_noop_stub},
    {"dma_sync_single_for_device", (void *)(uintptr_t)&kb_noop_stub},
    {"dump_stack", (void *)(uintptr_t)&kb_noop_stub},
    {"down", (void *)(uintptr_t)&kb_noop_stub},
    {"down_interruptible", (void *)(uintptr_t)&kb_return_zero},
    {"down_read_trylock", (void *)(uintptr_t)&kb_return_one},
    {"down_trylock", (void *)(uintptr_t)&kb_return_zero},
    {"down_write_trylock", (void *)(uintptr_t)&kb_return_one},
    {"downgrade_write", (void *)(uintptr_t)&kb_noop_stub},
    {"fasync_helper", (void *)(uintptr_t)&kb_return_zero},
    {"freezing_slow_path", (void *)(uintptr_t)&kb_return_zero},
    {"free_pages", (void *)(uintptr_t)&kb_noop_stub},
    {"get_device_system_crosststamp", (void *)(uintptr_t)&kb_return_zero},
    {"get_random_u32", (void *)(uintptr_t)&kb_return_zero},
    {"init_wait_var_entry", (void *)(uintptr_t)&kb_noop_stub},
    {"kstrtobool", (void *)(uintptr_t)&kb_return_zero},
    {"kstrtoint", (void *)(uintptr_t)&kb_return_zero},
    {"mempool_alloc", (void *)(uintptr_t)&kb_alloc_stub},
    {"mempool_create", (void *)(uintptr_t)&kb_alloc_stub},
    {"mempool_create_node", (void *)(uintptr_t)&kb_alloc_stub},
    {"mempool_destroy", (void *)(uintptr_t)&kb_free_first_arg_stub},
    {"mempool_free", (void *)(uintptr_t)&kb_free_first_arg_stub},
    {"mutex_lock_interruptible", (void *)(uintptr_t)&kb_mutex_lock_interruptible},
    {"mutex_lock_killable", (void *)(uintptr_t)&kb_mutex_lock_killable},
    {"mutex_is_locked", (void *)(uintptr_t)&kb_mutex_is_locked},
    {"sg_free_table", (void *)(uintptr_t)&kb_noop_stub},
    {"set_freezable", (void *)(uintptr_t)&kb_noop_stub},
    {"sme_active", (void *)(uintptr_t)&kb_return_zero},
    {"shrinker_alloc", (void *)(uintptr_t)&kb_alloc_stub},
    {"shrinker_free", (void *)(uintptr_t)&kb_noop_stub},
    {"shrinker_register", (void *)(uintptr_t)&kb_return_zero},
    {"stackleak_track_stack", (void *)(uintptr_t)&kb_stackleak_track_stack_stub},
    {"wake_up_var", (void *)(uintptr_t)&kb_noop_stub},
    {"warn_slowpath_null", (void *)(uintptr_t)&kb_noop_stub},
    {"__SCK__tp_func_block_bio_complete", (void *)(uintptr_t)&kb_noop_stub},
    {"__SCK__tp_func_block_bio_remap", (void *)(uintptr_t)&kb_noop_stub},
    {"__SCK__tp_func_nvme_sq", (void *)(uintptr_t)&kb_noop_stub},
    {"__SCK__tp_func_xhci_dbg_init", (void *)(uintptr_t)&kb_noop_stub},
    {"__SCK__tp_func_xhci_dbg_quirks", (void *)(uintptr_t)&kb_noop_stub},
    {"__SCT__tp_func_block_bio_complete", (void *)(uintptr_t)&kb_noop_stub},
    {"__SCT__tp_func_block_bio_remap", (void *)(uintptr_t)&kb_noop_stub},
    {"__SCT__tp_func_nvme_sq", (void *)(uintptr_t)&kb_noop_stub},
    {"__SCT__tp_func_xhci_dbg_init", (void *)(uintptr_t)&kb_noop_stub},
    {"__SCT__tp_func_xhci_dbg_quirks", (void *)(uintptr_t)&kb_noop_stub},
    {"__alloc_pages", (void *)(uintptr_t)&kb_kvm_alloc_pages_stub},
    {"__check_object_size", (void *)(uintptr_t)&kb_noop_stub},
    {"__copy_overflow", (void *)(uintptr_t)&kb_noop_stub},
    {"__folio_lock", (void *)(uintptr_t)&kb_noop_stub},
    {"__folio_put", (void *)(uintptr_t)&kb_noop_stub},
    {"__free_pages", (void *)(uintptr_t)&kb_noop_stub},
    {"__get_free_pages", (void *)(uintptr_t)&kb_alloc_stub},
    {"get_free_pages_noprof", (void *)(uintptr_t)&kb_alloc_stub},
    {"__io_uring_cmd_do_in_task", (void *)(uintptr_t)&kb_return_zero},
    {"__node_distance", (void *)(uintptr_t)&kb_return_zero},
    {"__put_user_4", (void *)(uintptr_t)&kb_linux_put_user_4},
    {"__put_user_8", (void *)(uintptr_t)&kb_linux_put_user_8},
    {"__put_devmap_managed_page_refs", (void *)(uintptr_t)&kb_noop_stub},
    {"__printk_ratelimit", (void *)(uintptr_t)&kb_return_one},
    {"__release_region", (void *)(uintptr_t)&kb_noop_stub},
    {"__request_region", (void *)(uintptr_t)&kb_alloc_stub},
    {"__srcu_read_lock", (void *)(uintptr_t)&kb_return_zero},
    {"__srcu_read_unlock", (void *)(uintptr_t)&kb_noop_stub},
    {"__trace_trigger_soft_disabled", (void *)(uintptr_t)&kb_return_zero},
    {"__virt_addr_valid", (void *)(uintptr_t)&kb_return_one},
    {"__wake_up", (void *)(uintptr_t)&kb_wake_up_waitqueue},
    {"add_uevent_var", (void *)(uintptr_t)&kb_return_zero},
    {"address_space_init_once", (void *)(uintptr_t)&kb_noop_stub},
    {"alloc_pages", (void *)(uintptr_t)&kb_kvm_alloc_pages_stub},
    {"alloc_workqueue", (void *)(uintptr_t)&kb_alloc_stub},
    {"bdev_end_io_acct", (void *)(uintptr_t)&kb_noop_stub},
    {"bio_associate_blkg", (void *)(uintptr_t)&kb_noop_stub},
    {"bio_integrity_map_user", (void *)(uintptr_t)&kb_return_zero},
    {"bio_split_to_limits", (void *)(uintptr_t)&kb_return_zero},
    {"blk_freeze_queue_start", (void *)(uintptr_t)&kb_noop_stub},
    {"blk_integrity_unregister", (void *)(uintptr_t)&kb_noop_stub},
    {"blk_mq_delay_kick_requeue_list", (void *)(uintptr_t)&kb_noop_stub},
    {"blk_mq_freeze_queue", (void *)(uintptr_t)&kb_noop_stub},
    {"blk_mq_freeze_queue_wait", (void *)(uintptr_t)&kb_noop_stub},
    {"blk_mq_quiesce_queue", (void *)(uintptr_t)&kb_noop_stub},
    {"blk_mq_quiesce_tagset", (void *)(uintptr_t)&kb_noop_stub},
    {"blk_mq_requeue_request", (void *)(uintptr_t)&kb_noop_stub},
    {"blk_mq_unfreeze_queue", (void *)(uintptr_t)&kb_noop_stub},
    {"blk_mq_unquiesce_queue", (void *)(uintptr_t)&kb_noop_stub},
    {"blk_mq_unquiesce_tagset", (void *)(uintptr_t)&kb_noop_stub},
    {"blk_mq_wait_quiesce_done", (void *)(uintptr_t)&kb_noop_stub},
    {"blk_rq_unmap_user", (void *)(uintptr_t)&kb_noop_stub},
    {"blk_steal_bios", (void *)(uintptr_t)&kb_noop_stub},
    {"blk_sync_queue", (void *)(uintptr_t)&kb_noop_stub},
    {"backlight_device_register", (void *)(uintptr_t)&kb_alloc_stub},
    {"backlight_device_unregister", (void *)(uintptr_t)&kb_noop_stub},
    {"bit_wait", (void *)(uintptr_t)&kb_noop_stub},
    {"bpf_trace_run1", (void *)(uintptr_t)&kb_noop_stub},
    {"bpf_trace_run2", (void *)(uintptr_t)&kb_noop_stub},
    {"bpf_trace_run3", (void *)(uintptr_t)&kb_noop_stub},
    {"bpf_trace_run4", (void *)(uintptr_t)&kb_noop_stub},
    {"bpf_trace_run5", (void *)(uintptr_t)&kb_noop_stub},
    {"bpf_trace_run6", (void *)(uintptr_t)&kb_noop_stub},
    {"bpf_trace_run8", (void *)(uintptr_t)&kb_noop_stub},
    {"capable", (void *)(uintptr_t)&kb_return_zero},
    {"call_rcu", (void *)(uintptr_t)&kb_noop_stub},
    {"cdev_device_add", (void *)(uintptr_t)&kb_return_zero},
    {"cdev_device_del", (void *)(uintptr_t)&kb_noop_stub},
    {"cleanup_srcu_struct", (void *)(uintptr_t)&kb_noop_stub},
    {"compat_ptr_ioctl", (void *)(uintptr_t)&kb_return_zero},
    {"crypto_alloc_kpp", (void *)(uintptr_t)&kb_alloc_stub},
    {"crypto_alloc_shash", (void *)(uintptr_t)&kb_crypto_alloc_shash_stub},
    {"crypto_destroy_tfm", (void *)(uintptr_t)&kb_noop_stub},
    {"crypto_req_done", (void *)(uintptr_t)&kb_noop_stub},
    {"crypto_shash_final", (void *)(uintptr_t)&kb_crypto_shash_final_stub},
    {"crypto_shash_setkey", (void *)(uintptr_t)&kb_return_zero},
    {"crypto_shash_tfm_digest", (void *)(uintptr_t)&kb_crypto_shash_tfm_digest_stub},
    {"crypto_shash_update", (void *)(uintptr_t)&kb_crypto_shash_update_stub},
    {"delayed_work_timer_fn", (void *)(uintptr_t)&kb_noop_stub},
    {"destroy_workqueue", (void *)(uintptr_t)&kb_noop_stub},
    {"dev_driver_string", (void *)(uintptr_t)&kb_empty_string},
    {"devm_kfree", (void *)(uintptr_t)&kb_noop_stub},
    {"dev_pm_qos_expose_latency_tolerance", (void *)(uintptr_t)&kb_return_zero},
    {"dev_pm_qos_hide_latency_tolerance", (void *)(uintptr_t)&kb_noop_stub},
    {"dev_pm_qos_update_user_latency_tolerance", (void *)(uintptr_t)&kb_return_zero},
    {"device_del", (void *)(uintptr_t)&kb_noop_stub},
    {"device_initialize", (void *)(uintptr_t)&kb_noop_stub},
    {"disk_uevent", (void *)(uintptr_t)&kb_noop_stub},
    {"dmi_match", (void *)(uintptr_t)&kb_return_zero},
    {"dmi_check_system", (void *)(uintptr_t)&kb_return_zero},
    {"dmi_first_match", (void *)(uintptr_t)&kb_return_zero},
    {"dmi_get_date", (void *)(uintptr_t)&kb_return_zero},
    {"dmi_get_system_info", (void *)(uintptr_t)&kb_empty_string},
    {"disable_irq", (void *)(uintptr_t)&kb_noop_stub},
    {"__drm_atomic_helper_crtc_destroy_state", (void *)(uintptr_t)&kb_noop_stub},
    {"__drm_atomic_helper_crtc_duplicate_state", (void *)(uintptr_t)&kb_alloc_stub},
    {"__drm_atomic_helper_plane_destroy_state", (void *)(uintptr_t)&kb_noop_stub},
    {"__drm_atomic_helper_plane_duplicate_state", (void *)(uintptr_t)&kb_alloc_stub},
    {"__drm_atomic_state_free", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_atomic_add_affected_connectors", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_add_affected_planes", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_commit", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_get_crtc_state", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_atomic_get_plane_state", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_atomic_helper_check", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_helper_connector_destroy_state", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_atomic_helper_connector_duplicate_state", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_atomic_helper_connector_reset", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_atomic_helper_crtc_reset", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_atomic_helper_disable_plane", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_helper_page_flip", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_helper_plane_reset", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_atomic_helper_set_config", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_helper_swap_state", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_helper_update_legacy_modeset_state", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_atomic_helper_update_plane", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_set_crtc_for_connector", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_set_crtc_for_plane", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_set_fb_for_plane", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_set_mode_prop_for_crtc", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_state_alloc", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_atomic_state_default_clear", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_atomic_state_default_release", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_atomic_state_init", (void *)(uintptr_t)&kb_return_zero},
    {"drm_compat_ioctl", (void *)(uintptr_t)&kb_drm_compat_ioctl},
    {"drm_connector_attach_encoder", (void *)(uintptr_t)&kb_return_zero},
    {"drm_connector_attach_vrr_capable_property", (void *)(uintptr_t)&kb_return_zero},
    {"drm_connector_cleanup", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_connector_init", (void *)(uintptr_t)&kb_return_zero},
    {"drm_connector_list_iter_begin", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_connector_list_iter_end", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_connector_list_iter_next", (void *)(uintptr_t)&kb_return_zero},
    {"drm_connector_register", (void *)(uintptr_t)&kb_return_zero},
    {"drm_connector_set_vrr_capable_property", (void *)(uintptr_t)&kb_return_zero},
    {"drm_connector_unregister", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_connector_update_edid_property", (void *)(uintptr_t)&kb_return_zero},
    {"drm_crtc_cleanup", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_crtc_init_with_planes", (void *)(uintptr_t)&kb_return_zero},
    {"drm_crtc_send_vblank_event", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_dev_alloc", (void *)(uintptr_t)&kb_drm_dev_alloc},
    {"drm_dev_put", (void *)(uintptr_t)&kb_drm_dev_put},
    {"drm_dev_register", (void *)(uintptr_t)&kb_drm_dev_register},
    {"drm_dev_unregister", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_edid_override_connector_update", (void *)(uintptr_t)&kb_return_zero},
    {"drm_encoder_cleanup", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_encoder_init", (void *)(uintptr_t)&kb_return_zero},
    {"drm_file_get_master", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_format_info", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_framebuffer_cleanup", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_framebuffer_init", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_object_free", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_gem_create_mmap_offset", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_handle_create", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_mmap_obj", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_object_lookup", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_gem_object_release", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_gem_prime_export", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_gem_prime_fd_to_handle", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_prime_handle_to_fd", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_prime_import", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_gem_private_object_init", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_vm_close", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_gem_vm_open", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_helper_hpd_irq_event", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_helper_mode_fill_fb_struct", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_helper_probe_single_connector_modes", (void *)(uintptr_t)&kb_return_zero},
    {"drm_ioctl", (void *)(uintptr_t)&kb_drm_ioctl},
    {"drm_kms_helper_hotplug_event", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_kms_helper_poll_disable", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_kms_helper_poll_fini", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_kms_helper_poll_init", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_master_put", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_mode_config_cleanup", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_mode_create", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_mode_create_dvi_i_properties", (void *)(uintptr_t)&kb_return_zero},
    {"drm_mode_object_find", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_mode_object_put", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_mode_probed_add", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_mode_set_name", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_mode_vrefresh", (void *)(uintptr_t)&kb_return_zero},
    {"drm_modeset_acquire_fini", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_modeset_acquire_init", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_modeset_backoff", (void *)(uintptr_t)&kb_return_zero},
    {"drm_modeset_drop_locks", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_modeset_lock_all", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_modeset_lock_all_ctx", (void *)(uintptr_t)&kb_return_zero},
    {"drm_modeset_unlock_all", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_object_attach_property", (void *)(uintptr_t)&kb_return_zero},
    {"drm_object_property_set_value", (void *)(uintptr_t)&kb_return_zero},
    {"drm_open", (void *)(uintptr_t)&kb_drm_open},
    {"drm_plane_cleanup", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_plane_create_alpha_property", (void *)(uintptr_t)&kb_return_zero},
    {"drm_plane_create_blend_mode_property", (void *)(uintptr_t)&kb_return_zero},
    {"drm_plane_create_rotation_property", (void *)(uintptr_t)&kb_return_zero},
    {"drm_poll", (void *)(uintptr_t)&kb_return_zero},
    {"drm_prime_gem_destroy", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_prime_pages_to_sg", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_property_blob_get", (void *)(uintptr_t)&kb_identity_ptr},
    {"drm_property_blob_put", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_property_create", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_property_create_enum", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_property_lookup_blob", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_property_replace_blob", (void *)(uintptr_t)&kb_return_zero},
    {"drm_read", (void *)(uintptr_t)&kb_return_zero},
    {"drm_release", (void *)(uintptr_t)&kb_drm_release},
    {"drm_universal_plane_init", (void *)(uintptr_t)&kb_return_zero},
    {"drm_vma_node_is_allowed", (void *)(uintptr_t)&kb_return_one},
    {"drm_vma_offset_lookup_locked", (void *)(uintptr_t)&kb_alloc_stub},
    {"drmm_mode_config_init", (void *)(uintptr_t)&kb_return_zero},
    {"__SCK__tp_func_dma_fence_emit", (void *)(uintptr_t)&kb_noop_stub},
    {"__SCT__tp_func_dma_fence_emit", (void *)(uintptr_t)&kb_noop_stub},
    {"__drm_printfn_seq_file", (void *)(uintptr_t)&kb_noop_stub},
    {"__drm_puts_seq_file", (void *)(uintptr_t)&kb_noop_stub},
    {"__drmm_universal_plane_alloc", (void *)(uintptr_t)&kb_drmm_universal_plane_alloc},
    {"__tracepoint_dma_fence_emit", (void *)(uintptr_t)&kb_tracepoint_dma_fence_emit},
    {"cc_mkdec", (void *)(uintptr_t)&kb_return_zero},
    {"dma_buf_export", (void *)(uintptr_t)&kb_alloc_stub},
    {"dma_fence_match_context", (void *)(uintptr_t)&kb_return_zero},
    {"dma_fence_signal_locked", (void *)(uintptr_t)&kb_return_zero},
    {"dma_fence_unwrap_first", (void *)(uintptr_t)&kb_return_zero},
    {"dma_fence_unwrap_next", (void *)(uintptr_t)&kb_return_zero},
    {"dma_fence_wait_timeout", (void *)(uintptr_t)&kb_return_one},
    {"dma_resv_test_signaled", (void *)(uintptr_t)&kb_return_one},
    {"dma_resv_wait_timeout", (void *)(uintptr_t)&kb_return_one},
    {"dma_sync_sg_for_device", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_add_edid_modes", (void *)(uintptr_t)&kb_return_zero},
    {"drm_add_modes_noedid", (void *)(uintptr_t)&kb_return_zero},
    {"drm_aperture_remove_conflicting_pci_framebuffers", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_helper_check_plane_state", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_helper_commit", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_helper_crtc_destroy_state", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_atomic_helper_crtc_duplicate_state", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_atomic_helper_damage_merged", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_helper_dirtyfb", (void *)(uintptr_t)&kb_return_zero},
    {"drm_atomic_helper_plane_destroy_state", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_atomic_helper_plane_duplicate_state", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_atomic_helper_shutdown", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_connector_attach_edid_property", (void *)(uintptr_t)&kb_return_zero},
    {"drm_cvt_mode", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_debugfs_create_files", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_dev_enter", (void *)(uintptr_t)&kb_drm_dev_enter},
    {"drm_dev_exit", (void *)(uintptr_t)&kb_drm_dev_exit},
    {"drm_dev_get", (void *)(uintptr_t)&kb_drm_dev_get},
    {"drm_dev_printk", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_dev_unplug", (void *)(uintptr_t)&kb_drm_dev_unplug},
    {"drm_do_get_edid", (void *)(uintptr_t)&kb_return_zero},
    {"drm_event_reserve_init", (void *)(uintptr_t)&kb_return_zero},
    {"drm_fbdev_generic_setup", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_gem_dmabuf_mmap", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_dmabuf_release", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_gem_dmabuf_vmap", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_dmabuf_vunmap", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_gem_fb_create_handle", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_fb_destroy", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_gem_free_mmap_offset", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_gem_lock_reservations", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_map_attach", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_map_detach", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_gem_map_dma_buf", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_mmap", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_shmem_create", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_gem_shmem_free", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_gem_shmem_get_pages_sgt", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_gem_shmem_get_sg_table", (void *)(uintptr_t)&kb_alloc_stub},
    {"drm_gem_shmem_mmap", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_shmem_pin", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_shmem_print_info", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_gem_shmem_unpin", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_gem_shmem_vm_ops", (void *)(uintptr_t)&kb_drm_gem_shmem_vm_ops},
    {"drm_gem_shmem_vmap", (void *)(uintptr_t)&kb_return_zero},
    {"drm_gem_shmem_vunmap", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_gem_unlock_reservations", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_gem_unmap_dma_buf", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_mm_init", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_mm_insert_node_in_range", (void *)(uintptr_t)&kb_return_zero},
    {"drm_mm_print", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_mm_remove_node", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_mm_takedown", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_mode_config_reset", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_plane_enable_fb_damage_clips", (void *)(uintptr_t)&kb_return_zero},
    {"drm_send_event", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_set_preferred_mode", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_simple_encoder_init", (void *)(uintptr_t)&kb_return_zero},
    {"drm_syncobj_add_point", (void *)(uintptr_t)&kb_return_zero},
    {"drm_syncobj_find", (void *)(uintptr_t)&kb_return_zero},
    {"drm_syncobj_find_fence", (void *)(uintptr_t)&kb_return_zero},
    {"drm_syncobj_free", (void *)(uintptr_t)&kb_noop_stub},
    {"drm_syncobj_replace_fence", (void *)(uintptr_t)&kb_noop_stub},
    {"drmm_kfree", (void *)(uintptr_t)&kb_drmm_kfree},
    {"drmm_kmalloc", (void *)(uintptr_t)&kb_drmm_kmalloc},
    {"pgprot_writecombine", (void *)(uintptr_t)&kb_identity_ptr},
    {"sg_alloc_table", (void *)(uintptr_t)&kb_return_zero},
    {"sync_file_create", (void *)(uintptr_t)&kb_return_zero},
    {"sync_file_get_fence", (void *)(uintptr_t)&kb_return_zero},
    {"video_firmware_drivers_only", (void *)(uintptr_t)&kb_return_zero},
    {"ww_mutex_lock_interruptible", (void *)(uintptr_t)&kb_return_zero},
    {"finish_wait", (void *)(uintptr_t)&kb_finish_wait},
    {"free_opal_dev", (void *)(uintptr_t)&kb_noop_stub},
    {"free_pages", (void *)(uintptr_t)&kb_noop_stub},
    {"full_name_hash", (void *)(uintptr_t)&kb_return_zero},
    {"get_device", (void *)(uintptr_t)&kb_identity_ptr},
    {"handle_sysrq", (void *)(uintptr_t)&kb_noop_stub},
    {"hwmon_device_unregister", (void *)(uintptr_t)&kb_noop_stub},
    {"i2c_add_adapter", (void *)(uintptr_t)&kb_return_zero},
    {"i2c_del_adapter", (void *)(uintptr_t)&kb_noop_stub},
    {"idr_get_next", (void *)(uintptr_t)&kb_return_zero},
    {"init_opal_dev", (void *)(uintptr_t)&kb_return_zero},
    {"init_srcu_struct", (void *)(uintptr_t)&kb_return_zero},
    {"init_wait_entry", (void *)(uintptr_t)&kb_init_wait_entry},
    {"io_uring_cmd_done", (void *)(uintptr_t)&kb_noop_stub},
    {"io_uring_cmd_import_fixed", (void *)(uintptr_t)&kb_return_zero},
    {"iov_iter_kvec", (void *)(uintptr_t)&kb_noop_stub},
    {"is_vmalloc_addr", (void *)(uintptr_t)&kb_return_zero},
    {"kernel_read", (void *)(uintptr_t)&kb_return_zero},
    {"kernel_write", (void *)(uintptr_t)&kb_return_zero},
    {"kill_fasync", (void *)(uintptr_t)&kb_noop_stub},
    {"kthread_create_on_node", (void *)(uintptr_t)&kb_kthread_create_on_node},
    {"kthread_should_stop", (void *)(uintptr_t)&kb_return_one},
    {"kthread_stop", (void *)(uintptr_t)&kb_return_zero},
    {"memchr_inv", (void *)(uintptr_t)&kb_return_zero},
    {"mempool_alloc_slab", (void *)(uintptr_t)&kb_alloc_stub},
    {"mempool_free_slab", (void *)(uintptr_t)&kb_free_first_arg_stub},
    {"memremap_compat_align", (void *)(uintptr_t)&kb_return_zero},
    {"migrate_vma_finalize", (void *)(uintptr_t)&kb_noop_stub},
    {"migrate_vma_pages", (void *)(uintptr_t)&kb_return_zero},
    {"migrate_vma_setup", (void *)(uintptr_t)&kb_return_zero},
    {"module_put", (void *)(uintptr_t)&kb_noop_stub},
    {"ns_to_timespec64", (void *)(uintptr_t)&kb_ns_to_timespec64_stub},
    {"numa_node", (void *)(uintptr_t)&kb_return_zero},
    {"noop_llseek", (void *)(uintptr_t)&kb_return_zero},
    {"opal_unlock_from_suspend", (void *)(uintptr_t)&kb_return_zero},
    {"on_each_cpu_cond_mask", (void *)(uintptr_t)&kb_noop_stub},
    {"out_of_line_wait_on_bit_lock", (void *)(uintptr_t)&kb_return_zero},
    {"param_get_uint", (void *)(uintptr_t)&kb_return_zero},
    {"param_set_uint", (void *)(uintptr_t)&kb_return_zero},
    {"param_set_uint_minmax", (void *)(uintptr_t)&kb_return_zero},
    {"pcibios_resource_to_bus", (void *)(uintptr_t)&kb_noop_stub},
    {"pci_clear_master", (void *)(uintptr_t)&kb_noop_stub},
    {"pci_free_p2pmem", (void *)(uintptr_t)&kb_noop_stub},
    {"pci_release_regions", (void *)(uintptr_t)&kb_noop_stub},
    {"pci_stop_and_remove_bus_device", (void *)(uintptr_t)&kb_noop_stub},
    {"out_of_line_wait_on_bit", (void *)(uintptr_t)&kb_return_zero},
    {"perf_trace_buf_alloc", (void *)(uintptr_t)&kb_alloc_stub},
    {"perf_trace_run_bpf_submit", (void *)(uintptr_t)&kb_noop_stub},
    {"prepare_to_wait", (void *)(uintptr_t)&kb_prepare_to_wait},
    {"prepare_to_wait_event", (void *)(uintptr_t)&kb_prepare_to_wait_event},
    {"prepare_to_wait_exclusive", (void *)(uintptr_t)&kb_prepare_to_wait_exclusive},
    {"proc_symlink", (void *)(uintptr_t)&kb_alloc_stub},
    {"put_device", (void *)(uintptr_t)&kb_noop_stub},
    {"rb_erase", (void *)(uintptr_t)&kb_rb_erase},
    {"rb_first", (void *)(uintptr_t)&kb_rb_first},
    {"rb_first_postorder", (void *)(uintptr_t)&kb_return_zero},
    {"rb_insert_color", (void *)(uintptr_t)&kb_rb_insert_color},
    {"rb_next", (void *)(uintptr_t)&kb_rb_next},
    {"rb_next_postorder", (void *)(uintptr_t)&kb_return_zero},
    {"rb_prev", (void *)(uintptr_t)&kb_rb_prev},
    {"radix_tree_delete", (void *)(uintptr_t)&kb_return_zero},
    {"radix_tree_gang_lookup", (void *)(uintptr_t)&kb_return_zero},
    {"radix_tree_insert", (void *)(uintptr_t)&kb_return_zero},
    {"radix_tree_lookup", (void *)(uintptr_t)&kb_return_zero},
    {"radix_tree_lookup_slot", (void *)(uintptr_t)&kb_return_zero},
    {"radix_tree_replace_slot", (void *)(uintptr_t)&kb_noop_stub},
    {"refcount_warn_saturate", (void *)(uintptr_t)&kb_noop_stub},
    {"release_firmware", (void *)(uintptr_t)&kb_noop_stub},
    {"firmware_request_nowarn", (void *)(uintptr_t)&kb_return_zero},
    {"request_firmware", (void *)(uintptr_t)&kb_return_zero},
    {"reset_control_reset", (void *)(uintptr_t)&kb_return_zero},
    {"sed_ioctl", (void *)(uintptr_t)&kb_return_zero},
    {"set_memory_uc", (void *)(uintptr_t)&kb_return_zero},
    {"set_memory_wb", (void *)(uintptr_t)&kb_return_zero},
    {"set_normalized_timespec64", (void *)(uintptr_t)&kb_noop_stub},
    {"set_page_dirty", (void *)(uintptr_t)&kb_return_zero},
    {"set_page_dirty_lock", (void *)(uintptr_t)&kb_return_zero},
    {"set_pages_array_uc", (void *)(uintptr_t)&kb_return_zero},
    {"set_pages_array_wb", (void *)(uintptr_t)&kb_return_zero},
    {"seq_lseek", (void *)(uintptr_t)&kb_return_zero},
    {"seq_printf", (void *)(uintptr_t)&kb_return_zero},
    {"seq_putc", (void *)(uintptr_t)&kb_return_zero},
    {"seq_puts", (void *)(uintptr_t)&kb_return_zero},
    {"seq_read", (void *)(uintptr_t)&kb_return_zero},
    {"seq_read_iter", (void *)(uintptr_t)&kb_return_zero},
    {"single_open", (void *)(uintptr_t)&kb_return_zero},
    {"single_release", (void *)(uintptr_t)&kb_return_zero},
    {"synchronize_rcu", (void *)(uintptr_t)&kb_noop_stub},
    {"rcu_barrier", (void *)(uintptr_t)&kb_noop_stub},
    {"synchronize_irq", (void *)(uintptr_t)&kb_noop_stub},
    {"synchronize_srcu", (void *)(uintptr_t)&kb_noop_stub},
    {"sysfs_create_link", (void *)(uintptr_t)&kb_return_zero},
    {"sysfs_remove_link", (void *)(uintptr_t)&kb_noop_stub},
    {"trace_event_buffer_commit", (void *)(uintptr_t)&kb_noop_stub},
    {"trace_event_buffer_reserve", (void *)(uintptr_t)&kb_alloc_stub},
    {"trace_event_printf", (void *)(uintptr_t)&kb_noop_stub},
    {"trace_event_raw_init", (void *)(uintptr_t)&kb_return_zero},
    {"trace_event_reg", (void *)(uintptr_t)&kb_return_zero},
    {"trace_handle_return", (void *)(uintptr_t)&kb_return_zero},
    {"trace_print_symbols_seq", (void *)(uintptr_t)&kb_return_zero},
    {"trace_raw_output_prep", (void *)(uintptr_t)&kb_return_zero},
    {"trace_seq_printf", (void *)(uintptr_t)&kb_return_zero},
    {"trace_seq_putc", (void *)(uintptr_t)&kb_noop_stub},
    {"try_module_get", (void *)(uintptr_t)&kb_return_one},
    {"up", (void *)(uintptr_t)&kb_noop_stub},
    {"unmap_mapping_range", (void *)(uintptr_t)&kb_noop_stub},
    {"unlock_page", (void *)(uintptr_t)&kb_noop_stub},
    {"vmap", (void *)(uintptr_t)&kb_alloc_stub},
    {"vm_get_page_prot", (void *)(uintptr_t)&kb_return_zero},
    {"vmalloc_to_page", (void *)(uintptr_t)&kb_return_zero},
    {"vm_insert_page", (void *)(uintptr_t)&kb_return_zero},
    {"vga_set_legacy_decoding", (void *)(uintptr_t)&kb_noop_stub},
    {"pm_runtime_allow", (void *)(uintptr_t)&kb_noop_stub},
    {"pm_runtime_forbid", (void *)(uintptr_t)&kb_noop_stub},
    {"__devm_request_region", (void *)(uintptr_t)&kb_alloc_stub},
    {"__get_user_1", (void *)(uintptr_t)&kb_linux_get_user_1},
    {"__get_user_2", (void *)(uintptr_t)&kb_linux_get_user_2},
    {"__get_user_4", (void *)(uintptr_t)&kb_linux_get_user_4},
    {"__get_user_8", (void *)(uintptr_t)&kb_linux_get_user_8},
    {"__kfifo_alloc", (void *)(uintptr_t)&kb_return_zero},
    {"__kfifo_free", (void *)(uintptr_t)&kb_kfifo_free},
    {"__kfifo_init", (void *)(uintptr_t)&kb_kfifo_init},
    {"__kfifo_in", (void *)(uintptr_t)&kb_kfifo_in},
    {"__kfifo_out", (void *)(uintptr_t)&kb_kfifo_out},
    {"__kfifo_to_user", (void *)(uintptr_t)&kb_kfifo_to_user},
    {"__pm_runtime_use_autosuspend", (void *)(uintptr_t)&kb_noop_stub},
    {"__put_cred", (void *)(uintptr_t)&kb_noop_stub},
    {"__put_task_struct", (void *)(uintptr_t)&kb_noop_stub},
    {"__suspend_report_result", (void *)(uintptr_t)&kb_noop_stub},
    {"add_device_randomness", (void *)(uintptr_t)&kb_noop_stub},
    {"add_wait_queue", (void *)(uintptr_t)&kb_add_wait_queue},
    {"add_wait_queue_exclusive", (void *)(uintptr_t)&kb_add_wait_queue_exclusive},
    {"blocking_notifier_call_chain", (void *)(uintptr_t)&kb_return_zero},
    {"blocking_notifier_chain_register", (void *)(uintptr_t)&kb_return_zero},
    {"blocking_notifier_chain_unregister", (void *)(uintptr_t)&kb_return_zero},
    {"bus_unregister", (void *)(uintptr_t)&kb_noop_stub},
    {"class_unregister", (void *)(uintptr_t)&kb_noop_stub},
    {"component_add", (void *)(uintptr_t)&kb_return_zero},
    {"component_del", (void *)(uintptr_t)&kb_noop_stub},
    {"current_time", (void *)(uintptr_t)&kb_return_zero},
    {"debugfs_create_dir", (void *)(uintptr_t)&kb_alloc_stub},
    {"debugfs_create_file", (void *)(uintptr_t)&kb_alloc_stub},
    {"debugfs_create_regset32", (void *)(uintptr_t)&kb_alloc_stub},
    {"debugfs_lookup_and_remove", (void *)(uintptr_t)&kb_return_zero},
    {"debugfs_remove", (void *)(uintptr_t)&kb_noop_stub},
    {"autoremove_wake_function", (void *)(uintptr_t)&kb_autoremove_wake_function},
    {"default_wake_function", (void *)(uintptr_t)&kb_default_wake_function},
    {"device_destroy", (void *)(uintptr_t)&kb_noop_stub},
    {"device_release_driver", (void *)(uintptr_t)&kb_noop_stub},
    {"device_remove_bin_file", (void *)(uintptr_t)&kb_noop_stub},
    {"device_remove_file", (void *)(uintptr_t)&kb_noop_stub},
    {"device_set_of_node_from_dev", (void *)(uintptr_t)&kb_noop_stub},
    {"device_set_wakeup_capable", (void *)(uintptr_t)&kb_noop_stub},
    {"device_unregister", (void *)(uintptr_t)&kb_noop_stub},
    {"driver_remove_file", (void *)(uintptr_t)&kb_noop_stub},
    {"fg_console", (void *)(uintptr_t)&kb_fg_console},
    {"gen_pool_add_owner", (void *)(uintptr_t)&kb_return_zero},
    {"gen_pool_dma_alloc", (void *)(uintptr_t)&kb_alloc_stub},
    {"gen_pool_dma_alloc_align", (void *)(uintptr_t)&kb_alloc_stub},
    {"gen_pool_free_owner", (void *)(uintptr_t)&kb_noop_stub},
    {"guid_parse", (void *)(uintptr_t)&kb_return_zero},
    {"idr_alloc", (void *)(uintptr_t)&kb_return_zero},
    {"idr_destroy", (void *)(uintptr_t)&kb_noop_stub},
    {"idr_remove", (void *)(uintptr_t)&kb_noop_stub},
    {"inode_set_ctime_current", (void *)(uintptr_t)&kb_noop_stub},
    {"init_task", (void *)(uintptr_t)&kb_init_task},
    {"iommu_get_domain_for_dev", (void *)(uintptr_t)&kb_return_zero},
    {"kernfs_notify", (void *)(uintptr_t)&kb_noop_stub},
    {"kernfs_put", (void *)(uintptr_t)&kb_noop_stub},
    {"kill_pid_usb_asyncio", (void *)(uintptr_t)&kb_noop_stub},
    {"kobject_create_and_add", (void *)(uintptr_t)&kb_alloc_stub},
    {"kobject_del", (void *)(uintptr_t)&kb_noop_stub},
    {"kobject_init_and_add", (void *)(uintptr_t)&kb_return_zero},
    {"kobject_put", (void *)(uintptr_t)&kb_noop_stub},
    {"kstrtou16", (void *)(uintptr_t)&kb_return_zero},
    {"kstrtou16_from_user", (void *)(uintptr_t)&kb_return_zero},
    {"kstrtou8", (void *)(uintptr_t)&kb_return_zero},
    {"kstrtoull", (void *)(uintptr_t)&kb_return_zero},
    {"no_seek_end_llseek", (void *)(uintptr_t)&kb_return_zero},
    {"overflowgid", (void *)(uintptr_t)&kb_overflowgid},
    {"overflowuid", (void *)(uintptr_t)&kb_overflowuid},
    {"param_get_string", (void *)(uintptr_t)&kb_return_zero},
    {"param_set_copystring", (void *)(uintptr_t)&kb_return_zero},
    {"phy_calibrate", (void *)(uintptr_t)&kb_return_zero},
    {"phy_exit", (void *)(uintptr_t)&kb_return_zero},
    {"phy_init", (void *)(uintptr_t)&kb_return_zero},
    {"phy_power_off", (void *)(uintptr_t)&kb_return_zero},
    {"phy_power_on", (void *)(uintptr_t)&kb_return_zero},
    {"phy_set_mode_ext", (void *)(uintptr_t)&kb_return_zero},
    {"pipe_lock", (void *)(uintptr_t)&kb_noop_stub},
    {"pipe_unlock", (void *)(uintptr_t)&kb_noop_stub},
    {"platform_device_put", (void *)(uintptr_t)&kb_noop_stub},
    {"platform_device_unregister", (void *)(uintptr_t)&kb_noop_stub},
    {"pm_runtime_no_callbacks", (void *)(uintptr_t)&kb_noop_stub},
    {"pm_runtime_set_autosuspend_delay", (void *)(uintptr_t)&kb_noop_stub},
    {"pm_wakeup_dev_event", (void *)(uintptr_t)&kb_noop_stub},
    {"print_hex_dump", (void *)(uintptr_t)&kb_noop_stub},
    {"put_pid", (void *)(uintptr_t)&kb_noop_stub},
    {"radix_tree_maybe_preload", (void *)(uintptr_t)&kb_return_zero},
    {"register_chrdev_region", (void *)(uintptr_t)&kb_return_zero},
    {"register_console", (void *)(uintptr_t)&kb_noop_stub},
    {"remove_wait_queue", (void *)(uintptr_t)&kb_remove_wait_queue},
    {"set_primary_fwnode", (void *)(uintptr_t)&kb_noop_stub},
    {"set_task_ioprio", (void *)(uintptr_t)&kb_noop_stub},
    {"sysfs_notify", (void *)(uintptr_t)&kb_noop_stub},
    {"sysfs_emit", (void *)(uintptr_t)&kb_snprintf_safe},
    {"sysfs_emit_at", (void *)(uintptr_t)&kb_sysfs_emit_at},
    {"sysfs_remove_file_from_group", (void *)(uintptr_t)&kb_noop_stub},
    {"sysfs_remove_group", (void *)(uintptr_t)&kb_noop_stub},
    {"sysfs_unbreak_active_protection", (void *)(uintptr_t)&kb_noop_stub},
    {"sysfs_unmerge_group", (void *)(uintptr_t)&kb_noop_stub},
    {"tasklist_lock", (void *)(uintptr_t)&kb_tasklist_lock},
    {"thp_get_unmapped_area", (void *)(uintptr_t)&kb_return_zero},
    {"trace_seq_acquire", (void *)(uintptr_t)&kb_return_zero},
    {"__trace_trigger_soft_disabled", (void *)(uintptr_t)&kb_return_zero},
    {"trace_event_buffer_commit", (void *)(uintptr_t)&kb_noop_stub},
    {"trace_event_buffer_reserve", (void *)(uintptr_t)&kb_alloc_stub},
    {"trace_event_printf", (void *)(uintptr_t)&kb_return_zero},
    {"trace_event_raw_init", (void *)(uintptr_t)&kb_return_zero},
    {"trace_event_reg", (void *)(uintptr_t)&kb_return_zero},
    {"trace_handle_return", (void *)(uintptr_t)&kb_noop_stub},
    {"trace_print_flags_seq", (void *)(uintptr_t)&kb_return_zero},
    {"trace_print_symbols_seq", (void *)(uintptr_t)&kb_return_zero},
    {"trace_raw_output_prep", (void *)(uintptr_t)&kb_return_zero},
    {"__audit_inode_child", (void *)(uintptr_t)&kb_noop_stub},
    {"tty_audit_add_data", (void *)(uintptr_t)&kb_noop_stub},
    {"tty_audit_push", (void *)(uintptr_t)&kb_noop_stub},
    {"tty_audit_tiocsti", (void *)(uintptr_t)&kb_noop_stub},
    {"vty_init", (void *)(uintptr_t)&kb_return_zero},
    {"virtio_check_mem_acc_cb", (void *)(uintptr_t)&kb_virtio_check_mem_acc_cb},
    {"virtio_reset_device", (void *)(uintptr_t)&kb_noop_stub},
    {"usb_amd_dev_put", (void *)(uintptr_t)&kb_noop_stub},
    {"usb_amd_quirk_pll_disable", (void *)(uintptr_t)&kb_noop_stub},
    {"usb_amd_quirk_pll_enable", (void *)(uintptr_t)&kb_noop_stub},
    {"usb_asmedia_modifyflowcontrol", (void *)(uintptr_t)&kb_noop_stub},
    {"yield", (void *)(uintptr_t)&kb_noop_stub},
    {"wait_for_random_bytes", (void *)(uintptr_t)&kb_return_zero},
    {"wait_woken", (void *)(uintptr_t)&kb_wait_woken},
    {"wake_up_bit", (void *)(uintptr_t)&kb_noop_stub},
    {"wake_up_process", (void *)(uintptr_t)&kb_wake_up_process},
    {"woken_wake_function", (void *)(uintptr_t)&kb_woken_wake_function},
    {"ww_mutex_lock", (void *)(uintptr_t)&kb_return_zero},
    {"ww_mutex_unlock", (void *)(uintptr_t)&kb_noop_stub},
    {"__xa_insert", (void *)(uintptr_t)&kb_return_zero},
    {"xa_destroy", (void *)(uintptr_t)&kb_noop_stub},
    {"xa_erase", (void *)(uintptr_t)&kb_return_zero},
    {"xa_find", (void *)(uintptr_t)&kb_return_zero},
    {"xa_find_after", (void *)(uintptr_t)&kb_return_zero},
    {"xa_load", (void *)(uintptr_t)&kb_return_zero},
    {"xa_store", (void *)(uintptr_t)&kb_return_zero},
};

const kb_linux_symbol_t *kb_linux_stub_symbols(size_t *out_count)
{
    if (out_count != NULL) {
        *out_count = sizeof(stub_symbols) / sizeof(stub_symbols[0]);
    }
    return stub_symbols;
}
