#include "linux_personality/linux_core_symbols.h"
#include "kobox/shim.h"
#include "linux_subsystem/kvm/kvm_symbols.h"

#include <stdint.h>

static unsigned long kb_identity_ulong(unsigned long value)
{
    return value;
}

static int kb_xen_domain_type;

static void *kb_serdev_tty_port_register(void *port, void *host, void *parent, void *driver, unsigned int index)
{
    (void)port;
    (void)host;
    (void)parent;
    (void)driver;
    (void)index;
    return (void *)(uintptr_t)(-19);
}

static int kb_serdev_tty_port_unregister(void *port)
{
    (void)port;
    return -19;
}

static const kb_linux_symbol_t symbols[] = {
    {"BUG_func", (void *)(uintptr_t)&kb_stack_chk_fail},
    {"_printk", (void *)(uintptr_t)&kb_printk},
    {"printk", (void *)(uintptr_t)&kb_printk},
    {"kfree", (void *)(uintptr_t)&kb_kfree},
    {"kmalloc", (void *)(uintptr_t)&kb_kmalloc},
    {"kzalloc", (void *)(uintptr_t)&kb_kzalloc},
    {"kmalloc_trace", (void *)(uintptr_t)&kb_kmalloc_trace},
    {"request_irq", (void *)(uintptr_t)&kb_request_irq},
    {"request_threaded_irq", (void *)(uintptr_t)&kb_request_threaded_irq},
    {"free_irq", (void *)(uintptr_t)&kb_free_irq},
    {"round_jiffies", (void *)(uintptr_t)&kb_identity_ulong},
    {"round_jiffies_relative", (void *)(uintptr_t)&kb_identity_ulong},
    {"__stack_chk_fail", (void *)(uintptr_t)&kb_stack_chk_fail},
    {"__ref_stack_chk_guard", (void *)(uintptr_t)&kb_ref_stack_chk_guard},
    {"__preempt_count", (void *)(uintptr_t)&kb_preempt_count},
    {"__num_online_cpus", (void *)(uintptr_t)&kb_num_online_cpus},
    {"__cpu_possible_mask", (void *)(uintptr_t)&kb_cpu_possible_mask},
    {"__cpu_present_mask", (void *)(uintptr_t)&kb_cpu_present_mask},
    {"USER_PTR_MAX", (void *)(uintptr_t)&kb_user_ptr_max},
    {"xen_domain_type", (void *)(uintptr_t)&kb_xen_domain_type},
    {"cpu_number", (void *)(uintptr_t)&kb_cpu_number},
    {"disable_hardirq", (void *)(uintptr_t)&kb_return_zero},
    {"disable_irq_nosync", (void *)(uintptr_t)&kb_disable_irq_nosync},
    {"enable_irq", (void *)(uintptr_t)&kb_enable_irq},
    {"irq_get_irq_data", (void *)(uintptr_t)&kb_irq_get_irq_data},
    {"irq_modify_status", (void *)(uintptr_t)&kb_irq_modify_status},
    {"__irq_apply_affinity_hint", (void *)(uintptr_t)&kb_irq_apply_affinity_hint},
    {"irq_set_affinity_hint", (void *)(uintptr_t)&kb_return_zero},
    {"_raw_spin_lock", (void *)(uintptr_t)&kb_raw_spin_lock},
    {"_raw_spin_trylock", (void *)(uintptr_t)&kb_raw_spin_trylock},
    {"_raw_spin_lock_irqsave", (void *)(uintptr_t)&kb_raw_spin_lock_irqsave},
    {"_raw_spin_unlock", (void *)(uintptr_t)&kb_raw_spin_unlock},
    {"_raw_spin_unlock_irqrestore", (void *)(uintptr_t)&kb_raw_spin_unlock_irqrestore},
    {"_raw_qspin_lock", (void *)(uintptr_t)&kb_raw_spin_lock},
    {"_raw_qspin_lock_irq", (void *)(uintptr_t)&kb_raw_spin_lock},
    {"_raw_qspin_lock_irqsave", (void *)(uintptr_t)&kb_raw_spin_lock_irqsave},
    {"_raw_qspin_unlock", (void *)(uintptr_t)&kb_raw_spin_unlock},
    {"_raw_qspin_unlock_irq", (void *)(uintptr_t)&kb_raw_spin_unlock},
    {"_raw_qspin_unlock_irqrestore", (void *)(uintptr_t)&kb_raw_spin_unlock_irqrestore},
    {"atomic_notifier_chain_register", (void *)(uintptr_t)&kb_atomic_notifier_chain_register},
    {"atomic_notifier_chain_unregister", (void *)(uintptr_t)&kb_atomic_notifier_chain_unregister},
    {"kexec_crash_loaded", (void *)(uintptr_t)&kb_kexec_crash_loaded},
    {"kstrtouint", (void *)(uintptr_t)&kb_kstrtouint},
    {"__kmalloc", (void *)(uintptr_t)&kb_kmalloc_alias},
    {"__kmalloc_cache_noprof", (void *)(uintptr_t)&kb_kmalloc_cache_noprof},
    {"__kmalloc_noprof", (void *)(uintptr_t)&kb_kmalloc_alias},
    {"__SCT__might_resched", (void *)(uintptr_t)&kb_might_resched},
    {"__sysfs_match_string", (void *)(uintptr_t)&kb_return_zero},
    {"__vmalloc_noprof", (void *)(uintptr_t)&kb_kzalloc},
    {"__kvmalloc_node_noprof", (void *)(uintptr_t)&kb_kzalloc},
    {"__ubsan_handle_load_invalid_value", (void *)(uintptr_t)&kb_ubsan_handle_load_invalid_value},
    {"__ubsan_handle_out_of_bounds", (void *)(uintptr_t)&kb_ubsan_handle_out_of_bounds},
    {"snprintf", (void *)(uintptr_t)&kb_snprintf_safe},
    {"sized_strscpy", (void *)(uintptr_t)&kb_sized_strscpy},
    {"strlcpy", (void *)(uintptr_t)&kb_strlcpy},
    {"skip_spaces", (void *)(uintptr_t)&kb_skip_spaces},
    {"string_get_size", (void *)(uintptr_t)&kb_string_get_size},
    {"strreplace", (void *)(uintptr_t)&kb_strreplace},
    {"vsnprintf", (void *)(uintptr_t)&kb_vsnprintf_safe},
    {"__SCT__cond_resched", (void *)(uintptr_t)&kb_cond_resched},
    {"__cond_resched_lock", (void *)(uintptr_t)&kb_return_zero},
    {"__alloc_percpu_gfp", (void *)(uintptr_t)&kb_alloc_percpu_gfp},
    {"__percpu_counter_sum", (void *)(uintptr_t)&kb_percpu_counter_sum_stub},
    {"__percpu_counter_init_many", (void *)(uintptr_t)&kb_percpu_counter_init_many_stub},
    {"__percpu_down_read", (void *)(uintptr_t)&kb_noop_stub},
    {"__percpu_init_rwsem", (void *)(uintptr_t)&kb_return_zero},
    {"__rcu_read_lock", (void *)(uintptr_t)&kb_noop_stub},
    {"__rcu_read_unlock", (void *)(uintptr_t)&kb_noop_stub},
    {"__smp_mb__before_atomic", (void *)(uintptr_t)&kb_noop_stub},
    {"__get_random_u32_below", (void *)(uintptr_t)&kb_get_random_u32_below},
    {"__get_task_comm", (void *)(uintptr_t)&kb_get_task_comm},
    {"__register_sysctl_init", (void *)(uintptr_t)&kb_register_sysctl_init},
    {"kill_pgrp", (void *)(uintptr_t)&kb_kill_pgrp},
    {"alloc_cpumask_var", (void *)(uintptr_t)&kb_alloc_cpumask_var},
    {"alloc_cpumask_var_node", (void *)(uintptr_t)&kb_alloc_cpumask_var},
    {"free_percpu", (void *)(uintptr_t)&kb_free_percpu},
    {"free_cpumask_var", (void *)(uintptr_t)&kb_free_cpumask_var},
    {"free_pages_exact", (void *)(uintptr_t)&kb_free_pages_exact},
    {"generate_random_uuid", (void *)(uintptr_t)&kb_generate_random_uuid},
    {"get_random_bytes", (void *)(uintptr_t)&kb_get_random_bytes},
    {"get_random_u16", (void *)(uintptr_t)&kb_get_random_u16},
    {"get_zeroed_page", (void *)(uintptr_t)&kb_alloc_stub},
    {"get_zeroed_page_noprof", (void *)(uintptr_t)&kb_alloc_stub},
    {"group_send_sig_info", (void *)(uintptr_t)&kb_group_send_sig_info},
    {"down_write", (void *)(uintptr_t)&kb_down_write},
    {"up_write", (void *)(uintptr_t)&kb_up_write},
    {"_find_next_bit", (void *)(uintptr_t)&kb_find_next_bit},
    {"find_next_bit", (void *)(uintptr_t)&kb_find_next_bit},
    {"_find_next_zero_bit", (void *)(uintptr_t)&kb_find_next_zero_bit},
    {"__bitmap_weight", (void *)(uintptr_t)&kb_bitmap_weight},
    {"__init_swait_queue_head", (void *)(uintptr_t)&kb_init_swait_queue_head},
    {"__init_waitqueue_head", (void *)(uintptr_t)&kb_init_waitqueue_head},
    {"__init_rwsem", (void *)(uintptr_t)&kb_init_rwsem},
    {"__alloc_percpu", (void *)(uintptr_t)&kb_alloc_percpu_gfp},
    {"alloc_pages_current", (void *)(uintptr_t)&kb_kvm_alloc_pages_stub},
    {"__kmalloc_node", (void *)(uintptr_t)&kb_kmalloc_node},
    {"__msecs_to_jiffies", (void *)(uintptr_t)&kb_msecs_to_jiffies},
    {"__ndelay", (void *)(uintptr_t)&kb_ndelay},
    {"__mutex_init", (void *)(uintptr_t)&kb_mutex_init},
    {"__warn_printk", (void *)(uintptr_t)&kb_printk},
    {"_raw_spin_lock_irq", (void *)(uintptr_t)&kb_raw_spin_lock},
    {"_raw_spin_unlock_irq", (void *)(uintptr_t)&kb_raw_spin_unlock},
    {"_raw_spin_lock_bh", (void *)(uintptr_t)&kb_raw_spin_lock},
    {"_raw_spin_unlock_bh", (void *)(uintptr_t)&kb_raw_spin_unlock},
    {"complete", (void *)(uintptr_t)&kb_complete},
    {"complete_all", (void *)(uintptr_t)&kb_complete_all},
    {"class_find_device", (void *)(uintptr_t)&kb_class_find_device},
    {"down_read", (void *)(uintptr_t)&kb_down_read},
    {"device_create", (void *)(uintptr_t)&kb_device_create},
    {"device_create_with_groups", (void *)(uintptr_t)&kb_device_create_with_groups},
    {"device_del", (void *)(uintptr_t)&kb_device_del},
    {"device_destroy", (void *)(uintptr_t)&kb_device_destroy},
    {"device_match_devt", (void *)(uintptr_t)&kb_device_match_devt},
    {"device_register", (void *)(uintptr_t)&kb_device_register},
    {"finish_wait", (void *)(uintptr_t)&kb_finish_wait},
    {"find_vpid", (void *)(uintptr_t)&kb_find_vpid},
    {"flush_work", (void *)(uintptr_t)&kb_flush_work},
    {"alloc_workqueue_noprof", (void *)(uintptr_t)&kb_alloc_stub},
    {"alloc_pages_exact", (void *)(uintptr_t)&kb_alloc_pages_exact},
    {"proc_dobool", (void *)(uintptr_t)&kb_proc_dobool},
    {"proc_dointvec", (void *)(uintptr_t)&kb_proc_dointvec},
    {"proc_dointvec_minmax", (void *)(uintptr_t)&kb_proc_dointvec_minmax},
    {"put_device", (void *)(uintptr_t)&kb_put_device},
    {"register_sysctl_sz", (void *)(uintptr_t)&kb_register_sysctl_sz},
    {"sysctl_vals", (void *)(uintptr_t)kb_sysctl_vals},
    {"unregister_sysctl_table", (void *)(uintptr_t)&kb_unregister_sysctl_table},
    {"__fortify_panic", (void *)(uintptr_t)&kb_stack_chk_fail},
    {"fortify_panic", (void *)(uintptr_t)&kb_stack_chk_fail},
    {"from_kgid", (void *)(uintptr_t)&kb_return_zero},
    {"from_kgid_munged", (void *)(uintptr_t)&kb_return_zero},
    {"from_kuid", (void *)(uintptr_t)&kb_return_zero},
    {"from_kuid_munged", (void *)(uintptr_t)&kb_return_zero},
    {"from_kprojid", (void *)(uintptr_t)&kb_return_zero},
    {"from_vfsgid", (void *)(uintptr_t)&kb_return_zero},
    {"from_vfsuid", (void *)(uintptr_t)&kb_return_zero},
    {"fs_param_is_gid", (void *)(uintptr_t)&kb_return_zero},
    {"fs_param_is_uid", (void *)(uintptr_t)&kb_return_zero},
    {"kfree_sensitive", (void *)(uintptr_t)&kb_kfree_sensitive},
    {"kmalloc_node_trace", (void *)(uintptr_t)&kb_kmalloc_node_trace},
    {"kmem_cache_alloc", (void *)(uintptr_t)&kb_kmem_cache_alloc},
    {"kmem_cache_alloc_trace", (void *)(uintptr_t)&kb_kmalloc_trace},
    {"kmemdup", (void *)(uintptr_t)&kb_kmemdup},
    {"mempool_kfree", (void *)(uintptr_t)&kb_kfree},
    {"mempool_kmalloc", (void *)(uintptr_t)&kb_kmalloc},
    {"memcpy_and_pad", (void *)(uintptr_t)&kb_memcpy_and_pad},
    {"memweight", (void *)(uintptr_t)&kb_memweight},
    {"mutex_lock", (void *)(uintptr_t)&kb_mutex_lock},
    {"mutex_lock_io", (void *)(uintptr_t)&kb_mutex_lock},
    {"mutex_lock_interruptible", (void *)(uintptr_t)&kb_mutex_lock_interruptible},
    {"mutex_lock_killable", (void *)(uintptr_t)&kb_mutex_lock_killable},
    {"mutex_is_locked", (void *)(uintptr_t)&kb_mutex_is_locked},
    {"mutex_trylock", (void *)(uintptr_t)&kb_mutex_trylock},
    {"mutex_unlock", (void *)(uintptr_t)&kb_mutex_unlock},
    {"wait_for_completion", (void *)(uintptr_t)&kb_wait_for_completion},
    {"wait_for_completion_interruptible", (void *)(uintptr_t)&kb_wait_for_completion},
    {"wait_for_completion_interruptible_timeout", (void *)(uintptr_t)&kb_wait_for_completion_io_timeout},
    {"wait_for_completion_io_timeout", (void *)(uintptr_t)&kb_wait_for_completion_io_timeout},
    {"__const_udelay", (void *)(uintptr_t)&kb_const_udelay},
    {"__udelay", (void *)(uintptr_t)&kb_udelay},
    {"__usecs_to_jiffies", (void *)(uintptr_t)&kb_usecs_to_jiffies},
    {"__vmalloc", (void *)(uintptr_t)&kb_kzalloc},
    {"cancel_delayed_work_sync", (void *)(uintptr_t)&kb_cancel_delayed_work_sync},
    {"cancel_delayed_work", (void *)(uintptr_t)&kb_cancel_delayed_work},
    {"cancel_work_sync", (void *)(uintptr_t)&kb_cancel_work_sync},
    {"capable", (void *)(uintptr_t)&kb_return_zero},
    {"disable_irq", (void *)(uintptr_t)&kb_disable_irq_nosync},
    {"hwmon_device_register_with_info", (void *)(uintptr_t)&kb_hwmon_device_register_with_info},
    {"ida_alloc_range", (void *)(uintptr_t)&kb_ida_alloc_range},
    {"ida_destroy", (void *)(uintptr_t)&kb_ida_destroy},
    {"ida_free", (void *)(uintptr_t)&kb_ida_free},
    {"ida_simple_get", (void *)(uintptr_t)&kb_ida_simple_get},
    {"ida_simple_remove", (void *)(uintptr_t)&kb_ida_simple_remove},
    {"init_timer_key", (void *)(uintptr_t)&kb_init_timer_key},
    {"jiffies_to_msecs", (void *)(uintptr_t)&kb_jiffies_to_msecs},
    {"jiffies_to_timespec64", (void *)(uintptr_t)&kb_jiffies_to_timespec64},
    {"jiffies_to_usecs", (void *)(uintptr_t)&kb_jiffies_to_usecs},
    {"kblockd_schedule_work", (void *)(uintptr_t)&kb_kblockd_schedule_work},
    {"kfree_const", (void *)(uintptr_t)&kb_kfree},
    {"in_group_p", (void *)(uintptr_t)&kb_return_zero},
    {"iov_iter_alignment", (void *)(uintptr_t)&kb_return_zero},
    {"is_current_pgrp_orphaned", (void *)(uintptr_t)&kb_return_zero},
    {"kmem_cache_create", (void *)(uintptr_t)&kb_kmem_cache_create},
    {"__kmem_cache_create_args", (void *)(uintptr_t)&kb_kmem_cache_create_args},
    {"kmem_cache_alloc_noprof", (void *)(uintptr_t)&kb_kmem_cache_alloc},
    {"kmem_cache_alloc_lru_noprof", (void *)(uintptr_t)&kb_kmem_cache_alloc},
    {"kmem_cache_destroy", (void *)(uintptr_t)&kb_kmem_cache_destroy},
    {"kmem_cache_free", (void *)(uintptr_t)&kb_kmem_cache_free},
    {"kmemdup_nul", (void *)(uintptr_t)&kb_kmemdup_nul},
    {"kmemdup_noprof", (void *)(uintptr_t)&kb_kmemdup},
    {"kmalloc_large", (void *)(uintptr_t)&kb_kmalloc_alias},
    {"ktime_get_with_offset", (void *)(uintptr_t)&kb_ktime_get_with_offset},
    {"ktime_get_coarse_real_ts64", (void *)(uintptr_t)&kb_ktime_get_real_ts64},
    {"ktime_get_real_seconds", (void *)(uintptr_t)&kb_ktime_get_real_seconds},
    {"ktime_get_raw_ts64", (void *)(uintptr_t)&kb_ktime_get_raw_ts64},
    {"ktime_get_real_ts64", (void *)(uintptr_t)&kb_ktime_get_real_ts64},
    {"kvfree_call_rcu", (void *)(uintptr_t)&kb_kfree},
    {"kvfree", (void *)(uintptr_t)&kb_kfree},
    {"kvmalloc_node", (void *)(uintptr_t)&kb_kzalloc},
    {"krealloc_noprof", (void *)(uintptr_t)&kb_krealloc_managed},
    {"list_sort", (void *)(uintptr_t)&kb_noop_stub},
    {"llist_add_batch", (void *)(uintptr_t)&kb_llist_add_batch},
    {"llist_del_first", (void *)(uintptr_t)&kb_llist_del_first},
    {"local_bh_disable", (void *)(uintptr_t)&kb_noop_stub},
    {"local_bh_enable", (void *)(uintptr_t)&kb_noop_stub},
    {"make_kgid", (void *)(uintptr_t)&kb_return_zero},
    {"make_kprojid", (void *)(uintptr_t)&kb_return_zero},
    {"make_kuid", (void *)(uintptr_t)&kb_return_zero},
    {"make_vfsgid", (void *)(uintptr_t)&kb_return_zero},
    {"make_vfsuid", (void *)(uintptr_t)&kb_return_zero},
    {"match_int", (void *)(uintptr_t)&kb_match_int},
    {"match_octal", (void *)(uintptr_t)&kb_match_octal},
    {"match_token", (void *)(uintptr_t)&kb_match_token},
    {"mod_timer", (void *)(uintptr_t)&kb_mod_timer},
    {"msleep", (void *)(uintptr_t)&kb_msleep},
    {"msleep_interruptible", (void *)(uintptr_t)&kb_msleep_interruptible},
    {"mempool_alloc_noprof", (void *)(uintptr_t)&kb_alloc_stub},
    {"mempool_create_node_noprof", (void *)(uintptr_t)&kb_alloc_stub},
    {"ndelay", (void *)(uintptr_t)&kb_ndelay},
    {"nsecs_to_jiffies", (void *)(uintptr_t)&kb_return_zero},
    {"ns_capable", (void *)(uintptr_t)&kb_return_zero},
    {"panic", (void *)(uintptr_t)&kb_stack_chk_fail},
    {"pid_task", (void *)(uintptr_t)&kb_pid_task},
    {"pid_vnr", (void *)(uintptr_t)&kb_pid_vnr},
    {"queue_delayed_work_on", (void *)(uintptr_t)&kb_queue_delayed_work_on},
    {"queue_work_on", (void *)(uintptr_t)&kb_queue_work_on},
    {"rcuwait_wake_up", (void *)(uintptr_t)&kb_noop_stub},
    {"round_jiffies_up", (void *)(uintptr_t)&kb_round_jiffies_up},
    {"schedule", (void *)(uintptr_t)&kb_run_deferred_work},
    {"schedule_hrtimeout", (void *)(uintptr_t)&kb_return_zero},
    {"io_schedule_timeout", (void *)(uintptr_t)&kb_schedule_timeout},
    {"schedule_timeout", (void *)(uintptr_t)&kb_schedule_timeout},
    {"schedule_timeout_interruptible", (void *)(uintptr_t)&kb_schedule_timeout},
    {"schedule_timeout_killable", (void *)(uintptr_t)&kb_schedule_timeout},
    {"send_signal_locked", (void *)(uintptr_t)&kb_send_signal_locked},
    {"serdev_tty_port_register", (void *)(uintptr_t)&kb_serdev_tty_port_register},
    {"serdev_tty_port_unregister", (void *)(uintptr_t)&kb_serdev_tty_port_unregister},
    {"timer_delete_sync", (void *)(uintptr_t)&kb_timer_delete},
    {"timer_shutdown_sync", (void *)(uintptr_t)&kb_timer_delete},
    {"up_read", (void *)(uintptr_t)&kb_up_read},
    {"usleep_range_state", (void *)(uintptr_t)&kb_usleep_range_state},
    {"vfree", (void *)(uintptr_t)&kb_kfree},
    {"vmalloc", (void *)(uintptr_t)&kb_kzalloc},
    {"vunmap", (void *)(uintptr_t)&kb_kfree},
    {"vzalloc", (void *)(uintptr_t)&kb_kzalloc},
    {"__list_add_valid_or_report", (void *)(uintptr_t)&kb_list_add_valid_or_report},
    {"__list_del_entry_valid_or_report", (void *)(uintptr_t)&kb_list_del_entry_valid_or_report},
    {"__list_add", (void *)(uintptr_t)&kb_list_add},
    {"list_del", (void *)(uintptr_t)&kb_list_del},
    {"__tasklet_hi_schedule", (void *)(uintptr_t)&kb_tasklet_schedule},
    {"__tasklet_schedule", (void *)(uintptr_t)&kb_tasklet_schedule},
    {"add_timer", (void *)(uintptr_t)&kb_add_timer},
    {"flush_delayed_work", (void *)(uintptr_t)&kb_flush_delayed_work},
    {"ktime_get", (void *)(uintptr_t)&kb_ktime_get},
    {"ktime_get_mono_fast_ns", (void *)(uintptr_t)&kb_ktime_get_mono_fast_ns},
    {"mod_delayed_work_on", (void *)(uintptr_t)&kb_mod_delayed_work_on},
    {"schedule_timeout_uninterruptible", (void *)(uintptr_t)&kb_schedule_timeout},
    {"tasklet_setup", (void *)(uintptr_t)&kb_tasklet_setup},
    {"timer_delete", (void *)(uintptr_t)&kb_timer_delete},
    {"percpu_counter_add_batch", (void *)(uintptr_t)&kb_percpu_counter_add_batch_stub},
    {"percpu_counter_destroy_many", (void *)(uintptr_t)&kb_noop_stub},
    {"percpu_down_write", (void *)(uintptr_t)&kb_noop_stub},
    {"percpu_free_rwsem", (void *)(uintptr_t)&kb_noop_stub},
    {"percpu_up_write", (void *)(uintptr_t)&kb_noop_stub},
    {"pcpu_alloc_noprof", (void *)(uintptr_t)&kb_alloc_percpu_gfp},
    {"wait_for_completion_killable_timeout", (void *)(uintptr_t)&kb_wait_for_completion_io_timeout},
    {"wait_for_completion_timeout", (void *)(uintptr_t)&kb_wait_for_completion_io_timeout},
};

const kb_linux_symbol_t *kb_linux_core_symbols(size_t *out_count)
{
    if (out_count != NULL) {
        *out_count = sizeof(symbols) / sizeof(symbols[0]);
    }
    return symbols;
}
