#pragma once

#include "kobox/device.h"

#include <stddef.h>
#include <stdint.h>

typedef struct kb_subsystem_dma_window_profile {
    uint64_t begin_calls;
    uint64_t mapping_calls;
    uint64_t mapping_cycles;
    uint64_t reuse_calls;
    uint64_t reuse_cycles;
    uint64_t end_calls;
    uint64_t mapped_bytes;
    uint64_t direct_mapping_calls;
    uint64_t direct_mapping_cycles;
    uint64_t direct_mapped_bytes;
    uint64_t staged_read_calls;
    uint64_t staged_bytes;
    uint64_t staging_copy_cycles;
} kb_subsystem_dma_window_profile_t;

kb_device_t *kb_subsystem_dma_default_device(kb_device_backend_t *backend);
void *kb_subsystem_dma_alloc(
    kb_device_backend_t *backend,
    kb_device_t *device,
    size_t size,
    uint64_t *dma_handle);
void kb_subsystem_dma_free(
    kb_device_backend_t *backend,
    size_t size,
    void *cpu_addr,
    uint64_t dma_handle);
void *kb_subsystem_dma_cpu_addr(uint64_t dma_addr, size_t *out_available);
uint64_t kb_subsystem_dma_map(
    kb_device_backend_t *backend,
    kb_device_t *device,
    void *cpu_addr,
    size_t size,
    kb_dma_dir_t direction,
    kb_status_t *out_status);
uint64_t kb_subsystem_dma_map_persistent_bidirectional(
    kb_device_backend_t *backend,
    kb_device_t *device,
    void *cpu_addr,
    size_t size,
    kb_status_t *out_status);
kb_status_t kb_subsystem_dma_map_pages(
    kb_device_backend_t *backend,
    kb_device_t *device,
    void *cpu_addr,
    size_t size,
    kb_dma_dir_t direction,
    uint64_t *out_page_dma,
    size_t out_capacity);
kb_status_t kb_subsystem_dma_preallocated_pages(
    kb_device_t *device,
    void *cpu_addr,
    size_t size,
    uint64_t *out_page_dma,
    size_t out_capacity);
kb_status_t kb_subsystem_dma_window_begin(
    kb_device_backend_t *backend,
    kb_device_t *device,
    void *cpu_addr,
    size_t size,
    kb_dma_dir_t direction);
kb_status_t kb_subsystem_dma_cached_window_begin(
    kb_device_backend_t *backend,
    kb_device_t *device,
    void *cpu_addr,
    size_t size,
    kb_dma_dir_t direction);
void kb_subsystem_dma_window_end(void);
void kb_subsystem_dma_cached_window_end(void);
void kb_subsystem_dma_cached_window_discard(void);
void kb_subsystem_dma_window_profile_snapshot(
    kb_subsystem_dma_window_profile_t *out_profile);
void kb_subsystem_dma_window_profile_record_staging(
    uint64_t bytes,
    uint64_t copy_cycles);
kb_status_t kb_subsystem_dma_map_fixed(
    kb_device_backend_t *backend,
    kb_device_t *device,
    void *cpu_addr,
    size_t size,
    uint64_t dma_addr,
    kb_dma_dir_t direction);
void kb_subsystem_dma_unmap(
    kb_device_backend_t *backend,
    kb_device_t *device,
    uint64_t dma_addr,
    size_t size,
    kb_dma_dir_t direction);
int kb_subsystem_dma_mapping_error(uint64_t dma_addr);
