#include "linux_subsystem/net/net_symbols.h"
#include "kobox/shim.h"

#include <stdint.h>

static unsigned char kb_softnet_data[4096];

static const kb_linux_symbol_t symbols[] = {
    {"softnet_data", (void *)(uintptr_t)kb_softnet_data},
    {"__rtnl_link_register", (void *)(uintptr_t)&kb_rtnl_link_register},
    {"__rtnl_link_unregister", (void *)(uintptr_t)&kb_rtnl_link_unregister},
    {"rtnl_link_unregister", (void *)(uintptr_t)&kb_rtnl_link_unregister},
    {"rtnl_lock", (void *)(uintptr_t)&kb_rtnl_lock},
    {"rtnl_unlock", (void *)(uintptr_t)&kb_rtnl_unlock},
    {"rtnl_is_locked", (void *)(uintptr_t)&kb_return_one},
    {"register_netdevice", (void *)(uintptr_t)&kb_register_netdevice},
    {"register_netdev", (void *)(uintptr_t)&kb_register_netdevice},
    {"unregister_netdev", (void *)(uintptr_t)&kb_noop_stub},
    {"unregister_netdevice_queue", (void *)(uintptr_t)&kb_noop_stub},
    {"alloc_netdev_mqs", (void *)(uintptr_t)&kb_alloc_netdev_mqs},
    {"alloc_etherdev_mqs", (void *)(uintptr_t)&kb_alloc_etherdev_mqs_rh},
    {"alloc_etherdev_mqs_rh", (void *)(uintptr_t)&kb_alloc_etherdev_mqs_rh},
    {"free_netdev", (void *)(uintptr_t)&kb_free_netdev},
    {"ether_setup", (void *)(uintptr_t)&kb_ether_setup},
    {"eth_mac_addr", (void *)(uintptr_t)&kb_eth_mac_addr},
    {"eth_validate_addr", (void *)(uintptr_t)&kb_eth_validate_addr},
    {"dev_addr_mod", (void *)(uintptr_t)&kb_dev_addr_mod},
    {"netif_carrier_on", (void *)(uintptr_t)&kb_netif_carrier_on},
    {"netif_carrier_off", (void *)(uintptr_t)&kb_netif_carrier_off},
    {"netif_device_attach", (void *)(uintptr_t)&kb_noop_stub},
    {"netif_device_detach", (void *)(uintptr_t)&kb_noop_stub},
    {"netif_napi_del", (void *)(uintptr_t)&kb_noop_stub},
    {"netif_set_real_num_rx_queues", (void *)(uintptr_t)&kb_return_zero},
    {"netif_set_real_num_tx_queues", (void *)(uintptr_t)&kb_return_zero},
    {"netif_set_xps_queue", (void *)(uintptr_t)&kb_return_zero},
    {"netif_schedule_queue", (void *)(uintptr_t)&kb_noop_stub},
    {"netif_tx_wake_queue", (void *)(uintptr_t)&kb_noop_stub},
    {"netif_wake_subqueue", (void *)(uintptr_t)&kb_noop_stub},
    {"dql_completed", (void *)(uintptr_t)&kb_noop_stub},
    {"dql_reset", (void *)(uintptr_t)&kb_noop_stub},
    {"consume_skb", (void *)(uintptr_t)&kb_consume_skb},
    {"__dev_kfree_skb_any", (void *)(uintptr_t)&kb_consume_skb},
    {"dev_kfree_skb_any_reason", (void *)(uintptr_t)&kb_consume_skb},
    {"dev_kfree_skb_irq_reason", (void *)(uintptr_t)&kb_consume_skb},
    {"kfree_skb", (void *)(uintptr_t)&kb_consume_skb},
    {"__alloc_skb", (void *)(uintptr_t)&kb_alloc_skb},
    {"__napi_alloc_skb", (void *)(uintptr_t)&kb_napi_alloc_skb},
    {"__netdev_alloc_skb", (void *)(uintptr_t)&kb_netdev_alloc_skb},
    {"skb_tstamp_tx", (void *)(uintptr_t)&kb_skb_tstamp_tx},
    {"skb_clone_tx_timestamp", (void *)(uintptr_t)&kb_skb_clone_tx_timestamp},
    {"csum_ipv6_magic", (void *)(uintptr_t)&kb_return_zero},
    {"skb_partial_csum_set", (void *)(uintptr_t)&kb_return_one},
    {"pskb_expand_head", (void *)(uintptr_t)&kb_return_zero},
    {"skb_put", (void *)(uintptr_t)&kb_skb_put},
    {"skb_to_sgvec", (void *)(uintptr_t)&kb_skb_to_sgvec},
    {"sg_next", (void *)(uintptr_t)&kb_sg_next},
    {"__pskb_pull_tail", (void *)(uintptr_t)&kb_pskb_pull_tail},
    {"___pskb_trim", (void *)(uintptr_t)&kb_return_zero},
    {"skb_copy_bits", (void *)(uintptr_t)&kb_skb_copy_bits},
    {"__skb_pad", (void *)(uintptr_t)&kb_return_zero},
    {"skb_trim", (void *)(uintptr_t)&kb_noop_stub},
    {"dev_lstats_read", (void *)(uintptr_t)&kb_dev_lstats_read},
    {"ethtool_op_get_ts_info", (void *)(uintptr_t)&kb_ethtool_op_get_ts_info},
    {"ethtool_op_get_link", (void *)(uintptr_t)&kb_return_one},
    {"__ethtool_get_link_ksettings", (void *)(uintptr_t)&kb_return_zero},
    {"ethtool_convert_link_mode_to_legacy_u32", (void *)(uintptr_t)&kb_return_zero},
    {"ethtool_convert_legacy_u32_to_link_mode", (void *)(uintptr_t)&kb_return_zero},
    {"netdev_err", (void *)(uintptr_t)&kb_dev_err},
    {"netdev_info", (void *)(uintptr_t)&kb_dev_warn},
    {"netdev_warn", (void *)(uintptr_t)&kb_dev_warn},
    {"__dynamic_netdev_dbg", (void *)(uintptr_t)&kb_dynamic_dev_dbg},
    {"netdev_rss_key_fill", (void *)(uintptr_t)&kb_get_random_bytes},
    {"netdev_master_upper_dev_link_rh", (void *)(uintptr_t)&kb_return_zero},
    {"netdev_rx_handler_register", (void *)(uintptr_t)&kb_return_zero},
    {"netdev_rx_handler_unregister", (void *)(uintptr_t)&kb_noop_stub},
    {"netdev_upper_dev_unlink", (void *)(uintptr_t)&kb_noop_stub},
    {"register_netdevice_notifier_rh", (void *)(uintptr_t)&kb_return_zero},
    {"unregister_netdevice_notifier_rh", (void *)(uintptr_t)&kb_return_zero},
    {"call_netdevice_notifiers", (void *)(uintptr_t)&kb_return_zero},
    {"dev_close", (void *)(uintptr_t)&kb_return_zero},
    {"dev_get_stats", (void *)(uintptr_t)&kb_return_zero},
    {"dev_trans_start", (void *)(uintptr_t)&kb_return_zero},
    {"dev_mc_sync_multiple", (void *)(uintptr_t)&kb_return_zero},
    {"dev_mc_unsync", (void *)(uintptr_t)&kb_noop_stub},
    {"dev_open", (void *)(uintptr_t)&kb_dev_open},
    {"dev_queue_xmit", (void *)(uintptr_t)&kb_dev_queue_xmit},
    {"dev_set_mtu", (void *)(uintptr_t)&kb_return_zero},
    {"dev_uc_sync_multiple", (void *)(uintptr_t)&kb_return_zero},
    {"dev_uc_unsync", (void *)(uintptr_t)&kb_noop_stub},
    {"netdev_change_features", (void *)(uintptr_t)&kb_return_zero},
    {"netdev_increment_features", (void *)(uintptr_t)&kb_return_zero},
    {"netdev_lower_state_changed", (void *)(uintptr_t)&kb_noop_stub},
    {"passthru_features_check", (void *)(uintptr_t)&kb_return_zero},
    {"vlan_uses_dev", (void *)(uintptr_t)&kb_return_zero},
    {"vlan_vid_add", (void *)(uintptr_t)&kb_return_zero},
    {"vlan_vid_del", (void *)(uintptr_t)&kb_return_zero},
    {"vlan_vids_add_by_dev", (void *)(uintptr_t)&kb_return_zero},
    {"vlan_vids_del_by_dev", (void *)(uintptr_t)&kb_return_zero},
    {"__netif_napi_add", (void *)(uintptr_t)&kb_netif_napi_add},
    {"netif_napi_add_weight", (void *)(uintptr_t)&kb_netif_napi_add},
    {"__napi_schedule", (void *)(uintptr_t)&kb_noop_stub},
    {"napi_complete_done", (void *)(uintptr_t)&kb_return_one},
    {"napi_disable", (void *)(uintptr_t)&kb_napi_disable},
    {"napi_enable", (void *)(uintptr_t)&kb_noop_stub},
    {"napi_gro_receive", (void *)(uintptr_t)&kb_napi_gro_receive},
    {"napi_schedule_prep", (void *)(uintptr_t)&kb_napi_schedule_prep},
    {"net_ratelimit", (void *)(uintptr_t)&kb_return_one},
    {"netdev_notify_peers", (void *)(uintptr_t)&kb_noop_stub},
    {"eth_commit_mac_addr_change", (void *)(uintptr_t)&kb_return_zero},
    {"eth_prepare_mac_addr_change", (void *)(uintptr_t)&kb_return_zero},
    {"eth_type_trans", (void *)(uintptr_t)&kb_return_zero},
    {"get_online_cpus", (void *)(uintptr_t)&kb_noop_stub},
    {"put_online_cpus", (void *)(uintptr_t)&kb_noop_stub},
    {"register_cpu_notifier", (void *)(uintptr_t)&kb_return_zero},
    {"unregister_cpu_notifier", (void *)(uintptr_t)&kb_return_zero},
    {"nf_conntrack_destroy", (void *)(uintptr_t)&kb_noop_stub},
};

const kb_linux_symbol_t *kb_linux_net_symbols(size_t *out_count)
{
    if (out_count != NULL) {
        *out_count = sizeof(symbols) / sizeof(symbols[0]);
    }
    return symbols;
}
