#include "linux_subsystem/block/block_symbols.h"
#include "kobox/shim.h"

#include <stdint.h>

static const kb_linux_symbol_t block_symbols[] = {
    {"sg_init_one", (void *)(uintptr_t)&kb_sg_init_one},
    {"sg_init_table", (void *)(uintptr_t)&kb_sg_init_one},
    {"sg_alloc_table_from_pages_segment", (void *)(uintptr_t)&kb_return_zero},
    {"sg_miter_next", (void *)(uintptr_t)&kb_sg_miter_next},
    {"sg_miter_skip", (void *)(uintptr_t)&kb_sg_miter_skip},
    {"sg_miter_start", (void *)(uintptr_t)&kb_sg_miter_start},
    {"sg_miter_stop", (void *)(uintptr_t)&kb_sg_miter_stop},
    {"sg_nents", (void *)(uintptr_t)&kb_sg_nents},
    {"sg_next", (void *)(uintptr_t)&kb_sg_next},
    {"sg_pcopy_from_buffer", (void *)(uintptr_t)&kb_return_zero},
    {"sg_pcopy_to_buffer", (void *)(uintptr_t)&kb_return_zero},
    {"__blk_alloc_disk", (void *)(uintptr_t)&kb_blk_alloc_disk},
    {"__blk_mq_alloc_disk", (void *)(uintptr_t)&kb_blk_mq_alloc_disk},
    {"__blk_rq_map_sg", (void *)(uintptr_t)&kb_return_zero},
    {"bdev_disk_changed", (void *)(uintptr_t)&kb_return_zero},
    {"bdev_start_io_acct", (void *)(uintptr_t)&kb_return_zero},
    {"blk_execute_rq", (void *)(uintptr_t)&kb_blk_execute_rq},
    {"blk_execute_rq_nowait", (void *)(uintptr_t)&kb_blk_execute_rq},
    {"blk_integrity_register", (void *)(uintptr_t)&kb_return_zero},
    {"blk_mark_disk_dead", (void *)(uintptr_t)&kb_blk_mark_disk_dead},
    {"blk_mq_alloc_request", (void *)(uintptr_t)&kb_blk_mq_alloc_request},
    {"blk_mq_alloc_request_hctx", (void *)(uintptr_t)&kb_blk_mq_alloc_request},
    {"blk_mq_alloc_tag_set", (void *)(uintptr_t)&kb_blk_mq_alloc_tag_set},
    {"blk_mq_complete_request", (void *)(uintptr_t)&kb_blk_mq_complete_request},
    {"blk_mq_complete_request_remote", (void *)(uintptr_t)&kb_blk_mq_complete_request_remote},
    {"blk_mq_destroy_queue", (void *)(uintptr_t)&kb_blk_mq_destroy_queue},
    {"blk_mq_end_request", (void *)(uintptr_t)&kb_blk_mq_end_request},
    {"blk_mq_end_request_batch", (void *)(uintptr_t)&kb_blk_mq_end_request_batch},
    {"blk_mq_free_request", (void *)(uintptr_t)&kb_blk_mq_free_request},
    {"blk_mq_free_tag_set", (void *)(uintptr_t)&kb_blk_mq_free_tag_set},
    {"blk_mq_freeze_queue_wait_timeout", (void *)(uintptr_t)&kb_return_zero},
    {"blk_mq_init_queue", (void *)(uintptr_t)&kb_blk_mq_init_queue},
    {"blk_mq_map_queues", (void *)(uintptr_t)&kb_blk_mq_map_queues},
    {"blk_mq_pci_map_queues", (void *)(uintptr_t)&kb_blk_mq_pci_map_queues},
    {"blk_mq_start_request", (void *)(uintptr_t)&kb_blk_mq_start_request},
    {"blk_mq_tagset_busy_iter", (void *)(uintptr_t)&kb_blk_mq_tagset_busy_iter},
    {"blk_mq_tagset_wait_completed_request", (void *)(uintptr_t)&kb_blk_mq_tagset_wait_completed_request},
    {"blk_mq_update_nr_hw_queues", (void *)(uintptr_t)&kb_blk_mq_update_nr_hw_queues},
    {"blk_op_str", (void *)(uintptr_t)&kb_empty_string},
    {"blk_put_queue", (void *)(uintptr_t)&kb_blk_put_queue},
    {"blk_queue_bounce_limit", (void *)(uintptr_t)&kb_blk_queue_bounce_limit},
    {"blk_queue_chunk_sectors", (void *)(uintptr_t)&kb_blk_queue_chunk_sectors},
    {"blk_queue_dma_alignment", (void *)(uintptr_t)&kb_blk_queue_dma_alignment},
    {"blk_queue_flag_set", (void *)(uintptr_t)&kb_blk_queue_flag_set},
    {"blk_queue_io_min", (void *)(uintptr_t)&kb_blk_queue_io_min},
    {"blk_queue_io_opt", (void *)(uintptr_t)&kb_blk_queue_io_opt},
    {"blk_queue_logical_block_size", (void *)(uintptr_t)&kb_blk_queue_logical_block_size},
    {"blk_queue_max_discard_sectors", (void *)(uintptr_t)&kb_blk_queue_max_discard_sectors},
    {"blk_queue_max_discard_segments", (void *)(uintptr_t)&kb_blk_queue_max_discard_segments},
    {"blk_queue_max_hw_sectors", (void *)(uintptr_t)&kb_blk_queue_max_hw_sectors},
    {"blk_queue_max_segments", (void *)(uintptr_t)&kb_blk_queue_max_segments},
    {"blk_queue_max_write_zeroes_sectors", (void *)(uintptr_t)&kb_blk_queue_max_write_zeroes_sectors},
    {"blk_queue_max_zone_append_sectors", (void *)(uintptr_t)&kb_blk_queue_max_zone_append_sectors},
    {"blk_queue_physical_block_size", (void *)(uintptr_t)&kb_blk_queue_physical_block_size},
    {"blk_queue_update_dma_alignment", (void *)(uintptr_t)&kb_blk_queue_update_dma_alignment},
    {"blk_queue_virt_boundary", (void *)(uintptr_t)&kb_blk_queue_virt_boundary},
    {"blk_queue_write_cache", (void *)(uintptr_t)&kb_blk_queue_write_cache},
    {"blk_revalidate_disk_zones", (void *)(uintptr_t)&kb_blk_revalidate_disk_zones},
    {"blk_rq_is_poll", (void *)(uintptr_t)&kb_return_zero},
    {"blk_rq_map_kern", (void *)(uintptr_t)&kb_blk_rq_map_kern},
    {"blk_rq_map_user_io", (void *)(uintptr_t)&kb_return_zero},
    {"blk_rq_map_user_iov", (void *)(uintptr_t)&kb_return_zero},
    {"blk_rq_poll", (void *)(uintptr_t)&kb_return_zero},
    {"blk_set_stacking_limits", (void *)(uintptr_t)&kb_blk_set_stacking_limits},
    {"blk_stack_limits", (void *)(uintptr_t)&kb_blk_stack_limits},
    {"blk_status_to_errno", (void *)(uintptr_t)&kb_blk_status_to_errno},
    {"blkdev_compat_ptr_ioctl", (void *)(uintptr_t)&kb_return_zero},
    {"device_add_disk", (void *)(uintptr_t)&kb_device_add_disk},
    {"del_gendisk", (void *)(uintptr_t)&kb_del_gendisk},
    {"disk_set_zoned", (void *)(uintptr_t)&kb_disk_set_zoned},
    {"disk_update_readahead", (void *)(uintptr_t)&kb_disk_update_readahead},
    {"ext_pi_type1_crc64", (void *)(uintptr_t)&kb_return_zero},
    {"ext_pi_type3_crc64", (void *)(uintptr_t)&kb_return_zero},
    {"put_disk", (void *)(uintptr_t)&kb_put_disk},
    {"set_capacity", (void *)(uintptr_t)&kb_set_capacity},
    {"set_capacity_and_notify", (void *)(uintptr_t)&kb_set_capacity_and_notify},
    {"set_disk_ro", (void *)(uintptr_t)&kb_set_disk_ro},
    {"scsi_add_host_with_dma", (void *)(uintptr_t)&kb_scsi_add_host_with_dma},
    {"scsi_done", (void *)(uintptr_t)&kb_scsi_done},
    {"scsi_done_direct", (void *)(uintptr_t)&kb_scsi_done},
    {"scsi_eh_prep_cmnd", (void *)(uintptr_t)&kb_scsi_eh_prep_cmnd},
    {"scsi_eh_restore_cmnd", (void *)(uintptr_t)&kb_scsi_eh_restore_cmnd},
    {"scsi_host_alloc", (void *)(uintptr_t)&kb_scsi_host_alloc},
    {"scsi_host_put", (void *)(uintptr_t)&kb_scsi_host_put},
    {"scsi_is_host_device", (void *)(uintptr_t)&kb_scsi_is_host_device},
    {"scsi_normalize_sense", (void *)(uintptr_t)&kb_scsi_normalize_sense},
    {"scsi_remove_host", (void *)(uintptr_t)&kb_scsi_remove_host},
    {"scsi_report_bus_reset", (void *)(uintptr_t)&kb_scsi_report_bus_reset},
    {"scsi_report_device_reset", (void *)(uintptr_t)&kb_scsi_report_device_reset},
    {"scsi_scan_host", (void *)(uintptr_t)&kb_scsi_scan_host},
    {"scsi_sense_desc_find", (void *)(uintptr_t)&kb_scsi_sense_desc_find},
    {"t10_pi_type1_crc", (void *)(uintptr_t)&kb_return_zero},
    {"t10_pi_type3_crc", (void *)(uintptr_t)&kb_return_zero},
};

const kb_linux_symbol_t *kb_linux_block_symbols(size_t *out_count)
{
    if (out_count != NULL) {
        *out_count = sizeof(block_symbols) / sizeof(block_symbols[0]);
    }
    return block_symbols;
}
